---
sidebar: sidebar 
permalink: concept-agents.html 
keywords: 'concept, connectors, learn about connectors, what are connectors, what is a connector, what"s a connector, days, 14 days, when is an agent required, agent supported locations, restricted mode, private mode, dark site, permissions, multiple agents, disaster recovery, agents, multiple agents, what is a Console agent' 
summary: コンソール エージェントを使用してNetApp Consoleをインフラストラクチャに接続し、AWS、Azure、Google Cloud、オンプレミス環境全体でストレージ ソリューションを安全にオーケストレーションし、データ保護サービスも利用できます。 
---
= NetApp Consoleエージェントについて学ぶ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
コンソール エージェントを使用して、 NetApp Consoleをインフラストラクチャに接続し、AWS、Azure、Google Cloud、オンプレミス環境全体でストレージ ソリューションを安全にオーケストレーションし、データ保護サービスを使用します。

コンソール エージェントを使用すると、次のことが可能になります。

* Cloud Volumes ONTAP のプロビジョニング、ストレージ ボリュームの設定、データ分類の使用など、 NetApp Consoleからストレージ管理タスクを調整します。
* サブスクリプション課金統合のためにクラウドプロバイダーのIAMロールを使用して認証する
* 高度なデータ サービス (NetApp Backup and Recovery、 NetApp Disaster Recovery、 NetApp Ransomware Resilience、 NetApp Cloud Tiering) を使用する


高度なオーケストレーションやデータ保護サービスが必要ない場合は、エージェントを導入せずに、オンプレミス ONTAP クラスタとクラウドネイティブ ストレージ サービスを一元管理できます。一部の監視およびデータ移動ツールは、エージェントなしでも使用できます。

次の表は、コンソール エージェントの有無にかかわらず使用できる機能とサービスを示しています。

[cols="40,20a,20a"]
|===
|  | エージェントで利用可能 | エージェントなしで利用可能 


3+| *サポートされているストレージ システム*: 


| Amazon FSx for ONTAP  a| 
はい（検出および管理機能）
 a| 
はい（検出のみ）



| Amazon S3 ストレージ  a| 
はい
 a| 
いいえ



| Azure BLOB ストレージ  a| 
はい
 a| 
はい



| Azure NetApp Files  a| 
はい
 a| 
はい



| Cloud Volumes ONTAP  a| 
はい
 a| 
いいえ



| Eシリーズシステム  a| 
はい
 a| 
いいえ



| Google Cloud NetApp Volumes  a| 
はい
 a| 
はい



| Google Cloud ストレージ バケット  a| 
はい
 a| 
いいえ



| StorageGRIDシステム  a| 
はい
 a| 
いいえ



| オンプレミスのONTAPクラスタ（高度な管理と検出）  a| 
はい（高度な管理と検出）
 a| 
いいえ（基本的な検出のみ）



3+| *ストレージ管理およびヘルスサービス*： 


| アラート  a| 
はい
 a| 
いいえ



| 自動化ハブ  a| 
はい
 a| 
はい



| Digital Advisor（Active IQ）  a| 
はい
 a| 
いいえ



| ライセンスとサブスクリプションの管理  a| 
はい
 a| 
いいえ



| 経済効率  a| 
はい
 a| 
いいえ



| ホームページダッシュボードのメトリクス  a| 
はい^2^
 a| 
いいえ



| ライフサイクルプランニング  a| 
はい
 a| 
いいえ^1^



| 持続可能性  a| 
はい
 a| 
いいえ



| ソフトウェアアップデート  a| 
はい
 a| 
はい



| NetAppワークロード  a| 
はい
 a| 
はい



3+| *利用可能なデータサービス*: 


| NetApp Backup and Recovery  a| 
はい
 a| 
いいえ



| NetApp Data Classification  a| 
はい
 a| 
いいえ



| NetApp Cloud Tiering  a| 
はい
 a| 
いいえ



| NetApp Copy and Sync  a| 
はい
 a| 
いいえ



| NetApp Disaster Recovery  a| 
はい
 a| 
いいえ



| NetApp Ransomware Resilience  a| 
はい
 a| 
いいえ



| NetApp Volume Caching  a| 
はい
 a| 
いいえ

|===
^1^ コンソール エージェントがなくてもライフサイクル プランニングを表示できますが、アクションを開始するにはコンソール エージェントが必要です。

^2^ ホーム ページで正確なメトリックを得るには、適切なサイズと構成のコンソール エージェントが必要です。



== コンソールエージェントは常に動作している必要があります

コンソール エージェントは、 NetApp Consoleの基本的な部分です。関連するエージェントが常に稼働し、動作し、アクセス可能であることを確認するのはお客様側の責任です。コンソールはエージェントの短時間の停止に対処できますが、インフラストラクチャの障害は迅速に修正する必要があります。

このドキュメントは EULA によって管理されます。ドキュメントの指示に従わずに製品を操作すると、製品の機能や EULA の権利に影響する可能性があります。



== サポートされている場所

エージェントは次の場所にインストールできます。

* Amazon Web Services
* Microsoft Azure
+
管理対象のCloud Volumes ONTAPシステムと同じリージョンの Azure にコンソール エージェントをデプロイします。あるいは、 https://docs.microsoft.com/en-us/azure/availability-zones/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies["Azure リージョン ペア"^] 。これにより、 Cloud Volumes ONTAPとそれに関連付けられたストレージ アカウント間で Azure Private Link 接続が使用されるようになります。 https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-enabling-private-link.html["Cloud Volumes ONTAP がAzure Private Link を使用する方法を学ぶ"^]

* Google Cloud
+
Google Cloud でコンソールとデータサービスを使用するには、Google Cloud にエージェントをデプロイします。

* お客様の敷地内




== クラウドプロバイダーとのコミュニケーション

エージェントは、AWS、Azure、Google Cloud へのすべての通信に TLS 1.3 を使用します。



== コンソールエージェントのインストール方法

コンソール エージェントは、コンソールから直接インストールすることも、クラウド プロバイダーのマーケットプレイスからインストールすることも、独自の Linux ホストまたは VCenter 環境にソフトウェアを手動でインストールすることもできます。

* link:concept-modes.html["NetApp Consoleの導入モードについて学ぶ"]
* link:task-quick-start-standard-mode.html["NetApp Consoleを標準モードで使い始める"]
* link:task-quick-start-restricted-mode.html["制限モードでNetApp Consoleを使い始める"]




== クラウドプロバイダーの権限

NetApp Consoleからコンソール エージェントを直接作成するには特定の権限が必要であり、コンソール エージェント自体には別の権限セットが必要です。コンソールから直接 AWS または Azure にコンソールエージェントを作成すると、コンソールは必要な権限を持つコンソールエージェントを作成します。

コンソールを標準モードで使用する場合、権限を付与する方法は、コンソール エージェントを作成する方法によって異なります。

権限の設定方法については、以下を参照してください。

* 標準モード
+
** link:concept-install-options-aws.html["AWS でのエージェントのインストールオプション"]
** link:concept-install-options-azure.html["Azure のエージェントのインストール オプション"]
** link:concept-install-options-google.html["Google Cloud のエージェントのインストール オプション"]
** link:task-install-agent-on-prem.html#agent-permission-aws-azure["オンプレミス展開用のクラウド権限を設定する"]


* link:task-prepare-restricted-mode.html#step-6-prepare-cloud-permissions["制限モードの権限を設定する"]


コンソール エージェントが日常の操作に必要な正確な権限を確認するには、次のページを参照してください。

* link:reference-permissions-aws.html["コンソールエージェントがAWS権限を使用する方法を学ぶ"]
* link:reference-permissions-azure.html["コンソールエージェントがAzureの権限を使用する方法を学ぶ"]
* link:reference-permissions-gcp.html["コンソール エージェントが Google Cloud 権限を使用する方法を説明します。"]


以降のリリースで新しい権限が追加された場合、コンソール エージェント ポリシーを更新するのはユーザーの責任となります。リリース ノートには新しい権限がリストされています。



== エージェントのアップグレード

NetApp は、機能の追加と安定性の向上のためにエージェント ソフトウェアを毎月更新します。  Cloud Volumes ONTAPやオンプレミスのONTAPクラスタ管理などの一部のコンソール機能は、コンソール エージェントのバージョンと設定に依存します。

エージェントをクラウドにインストールすると、インターネットにアクセスできる場合はコンソール エージェントが自動的に更新されます。



== オペレーティングシステムとVMのメンテナンス

コンソール エージェント ホスト上のオペレーティング システムの保守はお客様の責任となります。たとえば、お客様側では、会社の標準的なオペレーティング システム配布手順に従って、コンソール エージェント ホスト上のオペレーティング システムにセキュリティ更新を適用する必要があります。

マイナーなセキュリティ更新を適用するときに、コンソール gent ホスト上のサービスを停止する必要がないことに注意してください。

顧客がコンソール エージェント VM を停止してから起動する必要がある場合は、クラウド プロバイダーのコンソールから実行するか、オンプレミス管理の標準手順を使用して実行する必要があります。

<<agents-must-be-operational-at-all-times,コンソールエージェントは常に動作している必要があります>> 。



== 複数のシステムとエージェント

エージェントは複数のシステムを管理し、コンソールでデータ サービスをサポートできます。展開サイズと使用するデータ サービスに基づいて、単一のエージェントを使用して複数のシステムを管理できます。

大規模な導入の場合は、 NetApp の担当者と協力して環境のサイズを決定してください。問題が発生した場合は、 NetAppサポートにお問い合わせください。

エージェントの展開の例をいくつか示します。

* マルチクラウド環境 (AWS と Azure など) があり、AWS に 1 つのエージェントを配置し、Azure に別のエージェントを配置することを希望しています。それぞれが、それらの環境で実行されているCloud Volumes ONTAPシステムを管理します。
* サービス プロバイダーは、1 つのコンソール組織を使用して顧客にサービスを提供しながら、別の組織を使用してビジネス ユニットの 1 つに災害復旧サービスを提供する場合があります。各組織には独自のエージェントが必要です。

