---
sidebar: sidebar 
permalink: concept-agents.html 
keywords: 'concept, connectors, learn about connectors, what are connectors, what is a connector, what"s a connector, days, 14 days, when is a connector required, connector supported locations, restricted mode, private mode, dark site, permissions, multiple connectors, disaster recovery, agents, multiple agents, what is a Console agent' 
summary: _コンソール エージェント_ は、クラウド ネットワークまたはオンプレミス ネットワークで実行されるNetAppソフトウェアです。コンソール エージェントを使用して、 NetApp Consoleサービスをストレージ環境に接続します。 
---
= NetApp Consoleエージェントについて学ぶ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
_コンソール エージェント_ は、クラウド ネットワークまたはオンプレミス ネットワークで実行されます。コンソール エージェントを使用して、 NetApp Consoleサービスをストレージ環境に接続します。



== コンソールエージェントなしでできること

コンソール エージェントを展開しない場合でも、一部のコンソール機能とサービスが利用できます。

* Amazon FSx for NetApp ONTAP
+
一部のアクションには、コンソール エージェントまたはNetAppワークロード リンクが必要です。 https://docs.netapp.com/us-en/storage-management-fsx-ontap/start/concept-fsx-aws.html["コンソールエージェントまたはリンクが必要なアクションを確認する"^]

* 自動化ハブ
* Azure NetApp Files
+
Azure NetApp Files を管理するためにコンソール エージェントは必要ありませんが、 NetApp Data Classificationを使用してAzure NetApp Files をスキャンするにはコンソール エージェントが必要です。

* Google Cloud NetApp Volumes
* NetApp Copy and Sync
* デジタルアドバイザー
* ライセンスの使用状況を監視します。サブスクリプションの監視にはコンソールエージェントが必要です。
+
通常、コンソール エージェントなしでNetApp Consoleにライセンスを追加できます。

+
データは Cloud Cloud Volumes ONTAP Cloud Volumes ONTAP のノードベースのライセンスを追加するにはエージェントが必要です。

* オンプレミスのONTAPクラスタの直接検出
+
オンプレミスのONTAPクラスターをコンソールに追加するためにコンソール エージェントは必要ありませんが、追加のコンソール機能とデータ サービスにはコンソール エージェントが必要です。

+
https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-discovering-ontap.html["オンプレミスのONTAPクラスタの検出および管理オプションの詳細"^]

* ソフトウェアアップデート
* 持続可能性
* NetAppワークロード




== コンソールエージェントが必要な場合

標準モードでは、コンソールには次のコンソール エージェントが必要です。

* アラート
* Amazon FSx for ONTAP の管理機能
* Amazon S3 ストレージ
* Azure BLOB ストレージ
* NetApp Backup and Recovery
* データ分類
* Cloud Volumes ONTAP
* NetApp Disaster Recovery
* Eシリーズシステム
* 経済効率^1^
* Google Cloud Storage バケット
* オンプレミスのONTAPクラスタとNetAppデータ サービスの統合
* NetAppランサムウェア耐性
* StorageGRIDシステム
* NetApp Cloud Tiering
* NetApp Volume Caching


^1^ コンソール エージェントがなくてもこれらのサービスにアクセスできますが、アクションを開始するにはコンソール エージェントが必要です。

コンソールを制限モードで使用するには、常にコンソール エージェントが必要です。



== コンソールエージェントは常に動作している必要があります

コンソール エージェントは、 NetApp Consoleの基本的な部分です。関連するエージェントが常に稼働し、動作し、アクセス可能であることを確認するのはお客様側の責任です。コンソールはエージェントの短時間の停止に対処できますが、インフラストラクチャの障害は迅速に修正する必要があります。

このドキュメントは EULA によって管理されます。ドキュメントの指示に従わずに製品を操作すると、製品の機能や EULA の権利に影響する可能性があります。



== サポートされている場所

エージェントは次の場所にインストールできます。

* Amazon Web Services
* Microsoft Azure
+
管理対象のCloud Volumes ONTAPシステムと同じリージョンの Azure にコンソール エージェントをデプロイします。あるいは、 https://docs.microsoft.com/en-us/azure/availability-zones/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies["Azure リージョン ペア"^] 。これにより、 Cloud Volumes ONTAPとそれに関連付けられたストレージ アカウント間で Azure Private Link 接続が使用されるようになります。 https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-enabling-private-link.html["Cloud Volumes ONTAP がAzure Private Link を使用する方法を学ぶ"^]

* Google Cloud
+
Google Cloud でコンソールとデータサービスを使用するには、Google Cloud にエージェントをデプロイします。

* お客様の敷地内




== クラウドプロバイダーとのコミュニケーション

エージェントは、AWS、Azure、Google Cloud へのすべての通信に TLS 1.3 を使用します。



== 制限モード

コンソールを制限モードで使用するには、コンソール エージェントをインストールし、コンソール エージェント上でローカルに実行されているコンソール インターフェイスにアクセスします。

link:concept-modes.html["NetApp Consoleの導入モードについて学ぶ"] 。



== コンソールエージェントのインストール方法

コンソール エージェントは、コンソールから直接インストールすることも、クラウド プロバイダーのマーケットプレイスからインストールすることも、独自の Linux ホストまたは VCenter 環境にソフトウェアを手動でインストールすることもできます。開始方法は、コンソールを標準モードで使用するか、制限モードで使用するかによって異なります。

* link:concept-modes.html["NetApp Consoleの導入モードについて学ぶ"]
* link:task-quick-start-standard-mode.html["NetApp Consoleを標準モードで使い始める"]
* link:task-quick-start-restricted-mode.html["制限モードでNetApp Consoleを使い始める"]




== クラウド権限

NetApp Consoleからコンソール エージェントを直接作成するには特定の権限が必要であり、コンソール エージェント インスタンス自体には別の権限セットが必要です。コンソールから直接 AWS または Azure にコンソールエージェントを作成すると、コンソールは必要な権限を持つコンソールエージェントを作成します。

コンソールを標準モードで使用する場合、権限を付与する方法は、コンソール エージェントを作成する方法によって異なります。

権限の設定方法については、以下を参照してください。

* 標準モード
+
** link:concept-install-options-aws.html["AWS でのエージェントのインストールオプション"]
** link:concept-install-options-azure.html["Azure のエージェントのインストール オプション"]
** link:concept-install-options-google.html["Google Cloud のエージェントのインストール オプション"]
** link:task-install-agent-on-prem.html#agent-permission-aws-azure["オンプレミス展開用のクラウド権限を設定する"]


* link:task-prepare-restricted-mode.html#step-6-prepare-cloud-permissions["制限モードの権限を設定する"]


コンソール エージェントが日常の操作に必要な正確な権限を確認するには、次のページを参照してください。

* link:reference-permissions-aws.html["コンソールエージェントがAWS権限を使用する方法を学ぶ"]
* link:reference-permissions-azure.html["コンソールエージェントがAzureの権限を使用する方法を学ぶ"]
* link:reference-permissions-gcp.html["コンソール エージェントが Google Cloud 権限を使用する方法を説明します。"]


以降のリリースで新しい権限が追加された場合、コンソール エージェント ポリシーを更新するのはユーザーの責任となります。リリース ノートには新しい権限がリストされています。



== エージェントのアップグレード

NetApp は、機能の追加と安定性の向上のためにエージェント ソフトウェアを毎月更新します。  Cloud Volumes ONTAPやオンプレミスのONTAPクラスタ管理などの一部のコンソール機能は、コンソール エージェントのバージョンと設定に依存します。

標準モードまたは制限モードでは、インターネットにアクセスできる場合、コンソール エージェントは自動的に更新されます。



== オペレーティングシステムとVMのメンテナンス

コンソール エージェント ホスト上のオペレーティング システムの保守はお客様の責任となります。たとえば、お客様側では、会社の標準的なオペレーティング システム配布手順に従って、コンソール エージェント ホスト上のオペレーティング システムにセキュリティ更新を適用する必要があります。

マイナーなセキュリティ更新を適用するときに、コンソール gent ホスト上のサービスを停止する必要がないことに注意してください。

顧客がコンソール エージェント VM を停止してから起動する必要がある場合は、クラウド プロバイダーのコンソールから実行するか、オンプレミス管理の標準手順を使用して実行する必要があります。

<<agents-must-be-operational-at-all-times,コンソールエージェントは常に動作している必要があります>> 。



== 複数のシステムとエージェント

エージェントは複数のシステムを管理し、コンソールでデータ サービスをサポートできます。展開サイズと使用するデータ サービスに基づいて、単一のエージェントを使用して複数のシステムを管理できます。

大規模な導入の場合は、 NetApp の担当者と協力して環境のサイズを決定してください。問題が発生した場合は、 NetAppサポートにお問い合わせください。

エージェントの展開の例をいくつか示します。

* マルチクラウド環境 (AWS と Azure など) があり、AWS に 1 つのエージェントを配置し、Azure に別のエージェントを配置することを希望しています。それぞれが、それらの環境で実行されているCloud Volumes ONTAPシステムを管理します。
* サービス プロバイダーは、1 つのコンソール組織を使用して顧客にサービスを提供しながら、別の組織を使用してビジネス ユニットの 1 つに災害復旧サービスを提供する場合があります。各組織には独自のエージェントが必要です。

