---
sidebar: sidebar 
permalink: concept-iam-rbac.html 
keywords: roles, permissions, role-based access control, rbac, iam, identity and access management, least privilege, access control, NetApp Console access, organization access, folder access, project access, resource access 
summary: 'ロールベースのアクセス制御 (RBAC) を使用してNetApp Consoleへのユーザー アクセスを管理し、組織、フォルダ、またはプロジェクト レベルで事前定義されたロールを割り当てます。各ロールは、割り当てられたスコープ内でユーザーが実行できるアクションを定義する特定の権限を付与します。' 
---
= NetApp Consoleのロールベースアクセス制御（RBAC）について学ぶ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ロールベースのアクセス制御 (RBAC) を使用してNetApp Consoleへのユーザー アクセスを管理し、組織、フォルダ、またはプロジェクト レベルで事前定義されたロールを割り当てます。各ロールは、割り当てられたスコープ内でユーザーが実行できるアクションを定義する特定の権限を付与します。

NetApp は最小限の権限でコンソール ロールを設計しているため、各ロールにはそのタスクに必要な権限のみが含まれます。このアプローチでは、各メンバーが必要なものへのアクセスを制限することでセキュリティが強化されます。

リソースをフォルダーとプロジェクトに整理した後、組織のメンバーに特定のフォルダーまたはプロジェクトに対するロールを割り当て、メンバーが自分の責任のみを実行できるようにします。

たとえば、特定のプロジェクト レベルのランサムウェア レジリエンス管理者ロールをメンバーに割り当てて、組織全体へのより広範なアクセス権を付与することなく、そのプロジェクト内のリソースに対してランサムウェア レジリエンス操作を実行できるようにすることができます。同じユーザーに、組織内の複数のプロジェクトの役割を付与できます。

ユーザーの責任に応じて、同じスコープまたは異なるスコープに対して複数のロールを割り当てることができます。たとえば、小規模な組織では、同じユーザーが組織レベルでランサムウェア耐性とバックアップとリカバリの両方のタスクを管理する可能性がありますが、大規模な組織では、プロジェクト レベルで各ロールに異なるユーザーが割り当てられている可能性があります。



== コンソール組織メンバーの種類

NetApp Console 組織には、3 種類のメンバーがあります：

* _ユーザーアカウント_：NetApp Console にログインしてリソースを管理する個々のユーザー。ユーザーは、組織に追加される前に NetApp Console に登録する必要があります。
* _サービスアカウント_：アプリケーションまたはサービスが API 経由で NetApp Console とやり取りするために使用する非人間アカウント。サービス アカウントは、Console 組織に直接追加できます。
* _フェデレーショングループ_：IDプロバイダー（IdP）から同期されるグループで、複数のユーザーのアクセスをまとめて管理できます。フェデレーショングループ内の各ユーザーは、NetApp Consoleにサインアップし、アクセスロールを持つ組織に追加されてからでないと、グループに付与されたリソースにアクセスできません。


link:task-iam-manage-members-permissions.html#add-members["組織にメンバーを追加する方法を学びます。"]



== NetApp Consoleの事前定義されたロール

NetApp Consoleには、組織のメンバーに割り当てることができる定義済みのロールが含まれています。各ロールには、割り当てられた範囲 (組織、フォルダ、またはプロジェクト) 内でメンバーが実行できるアクションを指定する権限が含まれています。

NetApp Consoleのロールでは、メンバーがタスクに必要な権限のみを持つようにする最小権限の原則が採用されており、ロールは提供されるアクセスの種類によって分類されます。

* プラットフォームの役割: コンソール管理権限を付与する
* データ サービス ロール: ランサムウェア耐性やバックアップとリカバリなどの特定のデータ サービスを管理するための権限を提供します。
* アプリケーション ロール: ストレージの管理とコンソール イベントおよびアラートの監査の権限を提供します。


メンバーの責任に基づいて、複数の役割を割り当てることができます。たとえば、特定のプロジェクトに対して、メンバーにランサムウェア耐性管理者ロールとバックアップとリカバリ管理者ロールの両方を割り当てることができます。

link:reference-iam-predefined-roles.html["NetApp Consoleで利用可能な定義済みロールについて学習します"]。
