---
sidebar: sidebar 
permalink: reference-iam-storage-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, identity and access management, access roles, admin 
summary: ユーザーに次のロールを割り当てて、 NetAppコンソールのストレージ管理機能へのアクセスを許可できます。ユーザーに、ストレージを管理するための管理者ロールまたは監視するための閲覧者ロールを割り当てることができます。 
---
= NetAppコンソールのストレージアクセスロール
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ユーザーに次のロールを割り当てて、 NetAppコンソールのストレージ管理機能へのアクセスを許可できます。ユーザーに、ストレージを管理するための管理者ロールまたは監視するための閲覧者ロールを割り当てることができます。


NOTE: これらのロールは、 NetAppコンソール パートナーシップ API からは使用できません。

管理者は、次のストレージ リソースと機能についてユーザーにストレージ ロールを割り当てることができます。

ストレージ リソース:

* オンプレミスのONTAPクラスタ
* StorageGRID
* Eシリーズ


コンソールのサービスと機能:

* デジタルアドバイザー
* ソフトウェアアップデート
* ライフサイクルプランニング
* 持続可能性


.NetAppコンソールのストレージロールの例
多国籍企業である XYZ 社には、大規模なストレージ エンジニアとストレージ管理者のチームが存在します。これにより、このチームは、ユーザー管理、エージェントの作成、ライセンス管理などのコアコンソールタスクへのアクセスを制限しながら、担当リージョンのストレージ資産を管理できるようになります。

12 人のチーム内で、2 人のユーザーに *ストレージ閲覧者* ロールが付与され、割り当てられたコンソール プロジェクトに関連付けられたストレージ リソースを監視できるようになります。残りの 9 人には、ソフトウェア更新の管理、コンソール経由のONTAP System Manager へのアクセス、ストレージ リソースの検出 (システムの追加) などの機能を含む *Storage admin* ロールが付与されます。チームの 1 人に *システム ヘルス スペシャリスト* の役割が付与され、担当リージョン内のストレージ リソースのヘルスを管理できるようになりますが、システムを変更または削除することはできません。このユーザーは、割り当てられたプロジェクトのストレージ リソースに対してソフトウェア更新を実行することもできます。

組織には、ユーザー管理、エージェント作成、ライセンス管理など、コンソールのあらゆる側面を管理できる *組織管理者* ロールを持つ 2 人の追加ユーザーと、割り当てられているフォルダーとプロジェクトのコンソール管理タスクを実行できる *フォルダーまたはプロジェクト管理者* ロールを持つ複数のユーザーがいます。

次の表は、各ストレージ ロールが実行するアクションを示しています。

[cols="40,20a,20a,20a"]
|===
| 特徴とアクション | Storage Admin | システムヘルススペシャリスト | ストレージビューア 


4+| *ストレージ管理*: 


| 新しいリソースを発見する（システムを作成する）  a| 
はい
 a| 
はい
 a| 
いいえ



| 検出されたシステムを表示  a| 
はい
 a| 
はい
 a| 
いいえ



| コンソールからシステムを削除する  a| 
はい
 a| 
いいえ
 a| 
いいえ



| システムを変更する  a| 
はい
 a| 
いいえ
 a| 
いいえ



| *エージェントを作成する*  a| 
いいえ
 a| 
いいえ
 a| 
いいえ



4+| *デジタルアドバイザー* 


| すべてのページと機能を表示  a| 
はい
 a| 
はい
 a| 
はい



4+| *ライセンスとサブスクリプション* 


| すべてのページと機能を表示  a| 
いいえ
 a| 
いいえ
 a| 
いいえ



4+| *ソフトウェアアップデート* 


| ランディングページと推奨事項を表示  a| 
はい
 a| 
はい
 a| 
はい



| 潜在的なバージョンの推奨事項と主な利点を確認する  a| 
はい
 a| 
はい
 a| 
はい



| クラスターの更新の詳細を表示する  a| 
はい
 a| 
はい
 a| 
はい



| 更新前のチェックを実行し、アップグレードプランをダウンロードする  a| 
はい
 a| 
はい
 a| 
はい



| ソフトウェアアップデートをインストールする  a| 
はい
 a| 
はい
 a| 
いいえ



4+| *ライフサイクルプランニング* 


| キャパシティプランニングの状況を確認する  a| 
はい
 a| 
はい
 a| 
はい



| 次のアクションを選択する（ベストプラクティス、階層）  a| 
はい
 a| 
いいえ
 a| 
いいえ



| コールドデータをクラウドストレージに階層化してストレージを解放する  a| 
はい
 a| 
はい
 a| 
いいえ



| リマインダーを設定する  a| 
はい
 a| 
はい
 a| 
はい



4+| *持続可能性* 


| ダッシュボードと推奨事項を表示する  a| 
はい
 a| 
はい
 a| 
はい



| レポートデータをダウンロード  a| 
はい
 a| 
はい
 a| 
はい



| 炭素削減率を編集  a| 
はい
 a| 
はい
 a| 
いいえ



| 修正の推奨事項  a| 
はい
 a| 
はい
 a| 
いいえ



| 推奨を延期する  a| 
はい
 a| 
はい
 a| 
いいえ



4+| *システム管理者アクセス* 


| 資格情報を入力できます  a| 
はい
 a| 
はい
 a| 
いいえ



4+| *資格* 


| ユーザ クレデンシャル  a| 
はい
 a| 
はい
 a| 
いいえ

|===