---
sidebar: sidebar 
permalink: reference-networking-saas-console-previous.html 
keywords: networking, urls, endpoints, web browser, console, network, set up networking, netapp console 
summary: コンソールとインストールするエージェントが適切に機能するには、適切なネットワーク アクセスがあることを確認する必要があります。 
---
= 3.9.55 以前に必要なネットワーク アクセス
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Console、 NetApp Consoleエージェント、およびNetAppデータ サービスでは、必要なエンドポイントに接続するために、アウトバウンド インターネット アクセスが必要です。


NOTE: このトピックでは、 NetApp Console標準モード 3.9.55 以下のバージョンに必要なネットワーク アクセスについて説明します。  4.0.0以降に必要なエンドポイントについては、link:reference-networking-saas-console.html["4.0.0 以降に必要なエンドポイント"] 。

次のネットワーク アクセスを設定する必要があります。

* NetApp Consoleに SaaS (Software as a Service) としてアクセスするコンピュータ
* オンプレミスまたはクラウドにインストールするコンソール エージェント。




== エンドポイント リストを 4.0.0 以降の改訂リストに更新します。

バージョン 4.0.0 以降、コンソール エージェントに必要なエンドポイントが少なくなります。  4.0.0 より前の既存のデプロイメントは引き続きサポートされます。  4.0.0 以降にアップグレードした後、都合の良いときに古いエンドポイントを許可リストから削除できます。

NetApp、ファイアウォール ルールを更新して、サイズが小さく、より安全で、管理が容易な改訂版エンドポイント リストを使用することをお勧めします。  NetAppワイルドカード エントリの必要性がなくなり、エージェント アップグレードのエンドポイントはすべてのデータ サービスをサポートします。

[cols="3*"]
|===
| *3.9.55 以下のエンドポイント* | *4.0.0 以降のエンドポイント* | *目的* 


 a| 
* \https://support.netapp.com
* \https://mysupport.netapp.com

 a| 
* \https://mysupport.netapp.com
* \https://signin.b2c.netapp.com
* \https://support.netapp.com

 a| 
ライセンスおよびNetAppサポートへの連絡について。



 a| 
* \https://*.api.bluexp.netapp.com
* \https://api.bluexp.netapp.com
* \https://*.cloudmanager.cloud.netapp.com
* \https://cloudmanager.cloud.netapp.com
* \https://netapp-cloud-account.auth0.com
* \https://netapp-cloud-account.us.auth0.com
* \https://console.bluexp.netapp.com
* \https://*.console.bluexp.netapp.com

 a| 
* \https://api.bluexp.netapp.com
* \https://netapp-cloud-account.auth0.com
* \https://netapp-cloud-account.us.auth0.com
* \https://console.netapp.com
* \https://components.console.bluexp.netapp.com
* \https://cdn.auth0.com

 a| 
日常業務用。



 a| 
* \https://*.blob.core.windows.net
* \https://cloudmanagerinfraprod.azurecr.io

 a| 
* \https://bluexpinfraprod.eastus2.data.azurecr.io
* \https://bluexpinfraprod.azurecr.io

| コンソール エージェントのアップグレード用のイメージを取得します。 
|===
.手順
. エージェントのバージョンが 4.0.0 以上であることを確認します。link:task-troubleshoot-agent.html#view-the-console-agent-version["エージェントのバージョンを表示します。"]
. エンドポイントをホワイトリストに登録するlink:reference-networking-saas-console.html["4.0.0 以降でサポートされているエンドポイント"]。
. 次のコマンドを実行して、各エージェントのサービス マネージャー 2 サービスを再起動します。
+
[source, cli]
----
systemctl restart netapp-service-manager.service
----
. 次のコマンドを実行し、エージェントのステータスが _active(running)_ と表示されていることを確認します: _
+
[source, cli]
----
systemctl status netapp-service-manager.service
----
. ファイアウォールの許可リストから古いエンドポイントを削除します。




== NetApp Consoleおよびコンソール エージェント 3.9.55 以前のエンドポイント

これらのエンドポイントは、コンソール エージェント 3.9.55 以下に使用されます。

[cols="2*"]
|===
| エンドポイント | 目的 


 a| 
\https://support.netapp.com \https://mysupport.netapp.com
 a| 
ライセンス情報を取得し、 AutoSupportメッセージをNetAppサポートに送信します。



 a| 
\https://\*.api.bluexp.netapp.com \https://api.bluexp.netapp.com \https://*.cloudmanager.cloud.netapp.com \https://cloudmanager.cloud.netapp.com \https://netapp-cloud-account.auth0.com \https://netapp-cloud-account.us.auth0.com
| NetApp Console内で機能とサービスを提供します。 


 a| 
次の 2 つのエンドポイント セットから選択します。

* オプション1（推奨）
+
\https://bluexpinfraprod.eastus2.data.azurecr.io \https://bluexpinfraprod.azurecr.io

* オプション2
+
\https://*.blob.core.windows.net \https://cloudmanagerinfraprod.azurecr.io


 a| 
コンソール エージェントのアップグレード用のイメージを取得します。

NetApp、ランサムウェア耐性またはバックアップとリカバリを使用していない限り、より安全なオプション 1 のエンドポイントをファイアウォールで許可し、オプション 2 のエンドポイントを禁止することを推奨しています。これらのエンドポイントについては、次の点に注意してください。

* オプション 1 エンドポイントは 3.9.47 以降でサポートされます。  3.9.47 より前のリリースでは下位互換性がサポートされていません。
* コンソール エージェントは、まずオプション 2 のエンドポイントとの接続を開始します。これらのエンドポイントにアクセスできない場合は、オプション 1 のエンドポイントに自動的に接続します。
* コンソール エージェントをNetApp Backup and Recoveryまたは Ransomware Resilience と併用する場合、システムはオプション 1 のエンドポイントをサポートしません。オプション 2 のエンドポイントを許可し、オプション 1 を禁止します。


|===


== コンソールエージェントが接続するクラウドプロバイダーエンドポイント

コンソール エージェントがクラウド プロバイダーに展開されている場合、追加のエンドポイントにアクセスできる必要があります。

コンソール エージェントをインストールする前に、クラウド プロバイダーのエンドポイントへのアクセスを有効にします。

* link:task-install-agent-aws-console.html#networking-aws-agent["コンソールエージェントの AWS ネットワークアクセスを設定する"]
* link:task-install-agent-azure-console.html#networking-azure-agent["コンソール エージェントの Azure ネットワーク アクセスを設定する"]
* link:task-install-agent-google-console-gcloud.html#networking-gcp-agent["コンソール エージェントの Google Cloud ネットワーク アクセスを設定する"]


クラウド プロバイダーのエンドポイントはすべてのバージョンで同じです。



== コンソールエージェントが接続するデータサービスエンドポイント

コンソール エージェントでは、一部のNetAppデータ サービスとCloud Volumes ONTAP をサポートするために、追加の送信インターネット アクセスが必要です。



=== Cloud Volumes ONTAPのエンドポイント

* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-aws.html#outbound-internet-access-for-cloud-volumes-ontap-nodes["AWS のCloud Volumes ONTAPのエンドポイント"]
* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-azure.html["Azure のCloud Volumes ONTAPのエンドポイント"]
* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-gcp.html#outbound-internet-access["Google Cloud のCloud Volumes ONTAPのエンドポイント"]

