---
sidebar: sidebar 
permalink: reference-ports-gcp.html 
keywords: ports, firewall rules, http, https, inbound, outbound, connector, agent 
summary: エージェントの Google Cloud ファイアウォール ルールには、受信ルールと送信ルールの両方が必要です。  NetApp Consoleからコンソール エージェントを作成すると、このセキュリティ グループが自動的に作成されます。その他のインストール オプションの場合は、このセキュリティ グループを手動で設定する必要があります。 
---
= Google Cloud のエージェント ファイアウォール ルール
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
エージェントの Google Cloud ファイアウォール ルールには、受信ルールと送信ルールの両方が必要です。  NetApp Consoleからコンソール エージェントを作成すると、このセキュリティ グループが自動的に作成されます。その他のインストール オプションの場合は、このセキュリティ グループを手動で設定する必要があります。



== インバウンドルール

[cols="10,10,80"]
|===
| プロトコル | ポート | 目的 


| SSH | 22 | エージェントホストへのSSHアクセスを提供します 


| HTTP | 80  a| 
* クライアントのWebブラウザからローカルユーザーインターフェースへのHTTPアクセスを提供します
* Cloud Volumes ONTAPのアップグレードプロセス中に使用されます




| HTTPS | 443 | クライアントのWebブラウザからローカルユーザーインターフェースへのHTTPSアクセスを提供します 


| TCP | 3128 | Cloud Volumes ONTAPにインターネット アクセスを提供します。デプロイ後にこのポートを手動で開く必要があります。 
|===


== アウトバウンドルール

エージェントの事前定義されたファイアウォール ルールにより、すべての送信トラフィックが開かれます。許容できる場合は基本的な送信ルールに従います。より厳しい要件の場合は、高度な送信ルールを使用します。



=== 基本的なアウトバウンドルール

エージェントの定義済みファイアウォール ルールには、次の送信ルールが含まれます。

[cols="20,20,60"]
|===
| プロトコル | ポート | 目的 


| すべてのTCP | 全て | すべての送信トラフィック 


| すべてUDP | 全て | すべての送信トラフィック 
|===


=== 高度なアウトバウンドルール

送信トラフィックに厳格なルールが必要な場合は、次の情報を使用して、エージェントによる送信通信に必要なポートのみを開くことができます。


NOTE: 送信元 IP アドレスはエージェント ホストです。

[cols="5*"]
|===
| サービス | プロトコル | ポート | デスティネーション | 目的 


| API呼び出しとAutoSupport | HTTPS | 443 | アウトバウンドインターネットとONTAPクラスタ管理 LIF | Google Cloud、 ONTAP、 NetApp Data ClassificationへのAPI呼び出し、およびNetAppへのAutoSupportメッセージの送信 


| API呼び出し | TCP | 8080 | データ分類 | デプロイメント中にデータ分類インスタンスにプローブする 


| DNS | UDP | 53 | DNS | データ分類によるDNS解決に使用される 
|===