---
sidebar: sidebar 
permalink: reference-permissions-gcp.html 
keywords: permissions, gcp, gcp permissions, bluexp, console agent 
summary: コンソール エージェントには、クラウド プロバイダーでアクションを実行するための権限が必要です。これらの権限は、 NetAppが提供するポリシーに含まれています。エージェントがこれらの権限を使用して何を行うかを理解する必要があります。 
---
= NetApp Console エージェントの Google Cloud 権限
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
コンソール エージェントには、Google Cloud でアクションを実行するための権限が必要です。これらの権限は、 NetAppが提供するカスタム ロールに含まれています。エージェントがこれらの権限を使用して何を行うかを理解する必要があります。



== Google Cloud ユーザー アカウントの権限

以下のカスタムロールは、Google Cloud ユーザーにエージェントのデプロイに必要な権限を付与します。このカスタム ロールを、エージェントを展開するユーザーに適用します。

.Google Cloud ユーザー アカウントの権限を表示する
[%collapsible]
====
[source, yaml]
----
title: Console agent deployment policy
description: Permissions for the user who deploys the Console agent
stage: GA
includedPermissions:

- cloudbuild.builds.get
- compute.disks.create
- compute.disks.get
- compute.disks.list
- compute.disks.setLabels
- compute.disks.use
- compute.firewalls.create
- compute.firewalls.delete
- compute.firewalls.get
- compute.firewalls.list
- compute.globalOperations.get
- compute.images.get
- compute.images.getFromFamily
- compute.images.list
- compute.images.useReadOnly
- compute.instances.attachDisk
- compute.instances.create
- compute.instances.get
- compute.instances.list
- compute.instances.setDeletionProtection
- compute.instances.setLabels
- compute.instances.setMachineType
- compute.instances.setMetadata
- compute.instances.setTags
- compute.instances.start
- compute.instances.updateDisplayDevice
- compute.machineTypes.get
- compute.networks.get
- compute.networks.list
- compute.networks.updatePolicy
- compute.projects.get
- compute.regions.get
- compute.regions.list
- compute.subnetworks.get
- compute.subnetworks.list
- compute.zoneOperations.get
- compute.zones.get
- compute.zones.list
- config.deployments.create
- config.operations.get
- config.deployments.delete
- config.deployments.deleteState
- config.deployments.get
- config.deployments.getState
- config.deployments.list
- config.deployments.update
- config.deployments.updateState
- config.previews.get
- config.previews.list
- config.revisions.get
- config.resources.list
- deploymentmanager.compositeTypes.get
- deploymentmanager.compositeTypes.list
- deploymentmanager.deployments.create
- deploymentmanager.deployments.delete
- deploymentmanager.deployments.get
- deploymentmanager.deployments.list
- deploymentmanager.manifests.get
- deploymentmanager.manifests.list
- deploymentmanager.operations.get
- deploymentmanager.operations.list
- deploymentmanager.resources.get
- deploymentmanager.resources.list
- deploymentmanager.typeProviders.get
- deploymentmanager.typeProviders.list
- deploymentmanager.types.get
- deploymentmanager.types.list
- resourcemanager.projects.get
- compute.instances.setServiceAccount
- iam.serviceAccounts.actAs
- iam.serviceAccounts.create
- iam.serviceAccounts.list
- iam.serviceAccountKeys.create
- storage.buckets.create
- storage.buckets.get
- storage.objects.create
- storage.folders.create
- storage.objects.list

----
====


== サービスアカウントの権限

以下のカスタムロールは、コンソール エージェントに接続された Google Cloud サービス アカウントに、Google Cloud ネットワーク内のリソースとプロセスを管理するために必要な権限を付与します。

このカスタム ロールを、コンソール エージェント VM に接続されたサービス アカウントに適用します。

* link:task-install-agent-google-console-gcloud.html#agent-permissions-google["標準モードの Google Cloud 権限を設定する"]
* link:task-prepare-restricted-mode.html#step-6-prepare-cloud-permissions["制限モードの権限を設定する"]


.Google サービス アカウントの権限を表示する
[%collapsible]
====
後続のリリースで新しい権限が追加または削除されるので、ロールが最新であることを確認します。変更ログには、必要な新しい権限がすべてリストされます。link:reference-permissions-gcp.html#gcp-permissions-change-log["Google の権限変更ログを確認する"] link:task-adding-gcp-accounts.html["Google Cloud サービス アカウントを追加する方法を確認する"]

[source, yaml]
----
title: NetApp Console agent
description: Permissions for the service account associated with the Console agent.
stage: GA
includedPermissions:
- cloudbuild.builds.get
- cloudbuild.connections.list
- cloudbuild.repositories.accessReadToken
- cloudbuild.repositories.list
- cloudbuild.workerpools.list
- cloudbuild.workerpools.get
- cloudquotas.quotas.get
- cloudkms.cryptoKeys.getIamPolicy
- cloudkms.cryptoKeys.setIamPolicy
- cloudkms.keyRings.get
- cloudkms.keyRings.getIamPolicy
- cloudkms.keyRings.setIamPolicy
- config.artifacts.import
- config.deployments.create
- config.deployments.delete
- config.deployments.deleteState
- config.deployments.get
- config.deployments.getLock
- config.deployments.getState
- config.deployments.list
- config.deployments.lock
- config.deployments.update
- config.deployments.updateState
- config.previews.upload
- config.revisions.get
- config.revisions.getState
- config.operations.get
- config.previews.get
- config.previews.list
- config.resources.list
- compute.regionBackendServices.create
- compute.regionBackendServices.get
- compute.regionBackendServices.list
- compute.regionBackendServices.update
- compute.networks.updatePolicy
- compute.addresses.createInternal
- compute.addresses.deleteInternal
- compute.addresses.list
- compute.addresses.setLabels
- compute.addresses.useInternal
- compute.backendServices.create
- compute.disks.create
- compute.disks.createSnapshot
- compute.disks.delete
- compute.disks.get
- compute.disks.list
- compute.disks.setLabels
- compute.disks.update
- compute.disks.use
- compute.firewalls.create
- compute.firewalls.delete
- compute.firewalls.get
- compute.firewalls.list
- compute.forwardingRules.create
- compute.forwardingRules.delete
- compute.forwardingRules.get
- compute.forwardingRules.setLabels
- compute.forwardingRules.update
- compute.globalOperations.get
- compute.healthChecks.create
- compute.healthChecks.delete
- compute.healthChecks.get
- compute.healthChecks.useReadOnly
- compute.images.get
- compute.images.getFromFamily
- compute.images.list
- compute.images.useReadOnly
- compute.instances.addAccessConfig
- compute.instances.attachDisk
- compute.instances.create
- compute.instances.delete
- compute.instances.detachDisk
- compute.instances.get
- compute.instances.getSerialPortOutput
- compute.instances.list
- compute.instances.setDeletionProtection
- compute.instances.setLabels
- compute.instances.setMachineType
- compute.instances.setMetadata
- compute.instances.setTags
- compute.instances.start
- compute.instances.stop
- compute.instances.updateDisplayDevice
- compute.instances.use
- compute.instanceGroups.create
- compute.instanceGroups.delete
- compute.instanceGroups.get
- compute.instanceGroups.update
- compute.instanceGroups.use
- compute.addresses.get
- compute.instances.updateNetworkInterface
- compute.instances.setMinCpuPlatform
- compute.machineTypes.get
- compute.networks.get
- compute.networks.list
- compute.projects.get
- compute.regions.get
- compute.regions.list
- compute.regionBackendServices.delete
- compute.regionBackendServices.use
- compute.resourcePolicies.create
- compute.resourcePolicies.delete
- compute.resourcePolicies.get
- compute.snapshots.create
- compute.snapshots.delete
- compute.snapshots.get
- compute.snapshots.list
- compute.snapshots.setLabels
- compute.subnetworks.get
- compute.subnetworks.list
- compute.subnetworks.use
- compute.subnetworks.useExternalIp
- compute.zoneOperations.get
- compute.zones.get
- compute.zones.list
- compute.instances.setServiceAccount
- deploymentmanager.compositeTypes.get
- deploymentmanager.compositeTypes.list
- deploymentmanager.deployments.create
- deploymentmanager.deployments.delete
- deploymentmanager.deployments.get
- deploymentmanager.deployments.list
- deploymentmanager.manifests.get
- deploymentmanager.manifests.list
- deploymentmanager.operations.get
- deploymentmanager.operations.list
- deploymentmanager.resources.get
- deploymentmanager.resources.list
- deploymentmanager.typeProviders.get
- deploymentmanager.typeProviders.list
- deploymentmanager.types.get
- deploymentmanager.types.list
- logging.logEntries.list
- logging.privateLogEntries.list
- logging.logEntries.create
- logging.logEntries.route
- monitoring.timeSeries.list
- resourcemanager.projects.get
- storage.buckets.create
- storage.buckets.delete
- storage.buckets.get
- storage.buckets.list
- storage.objects.create
- storage.objects.delete
- storage.objects.get
- storage.objects.list
- storage.objects.update
- cloudkms.cryptoKeyVersions.useToEncrypt
- cloudkms.cryptoKeys.get
- cloudkms.cryptoKeys.list
- cloudkms.keyRings.list
- storage.buckets.update
- iam.serviceAccounts.actAs
- iam.serviceAccounts.create
- iam.serviceAccounts.get
- iam.serviceAccounts.getIamPolicy
- iam.serviceAccounts.list
- iam.serviceAccountKeys.create
- storage.buckets.getIamPolicy



----
====


== Google Cloud の権限の使用方法

コンソール エージェントは、カスタムロールの権限を使用して、Google Cloud ネットワーク内のCloud Volumes ONTAPリソースとNetAppデータサービス プロセスを管理します。次のセクションでは、エージェントがこれらの権限をどのように使用するかについて説明します。



=== Cloud Volumes ONTAPで使用される権限

コンソール エージェントは、カスタム ロールの権限を使用して、Google Cloud ネットワーク内のCloud Volumes ONTAP のリソースとプロセスを管理します。次のセクションでは、エージェントがこれらの権限をどのように使用するかについて説明します。

.Cloud Volumes ONTAPの権限
[%collapsible]
====
[cols="5*"]
|===
| アクション | 目的 | 展開に使用されますか? | 日常業務に使用されますか? | 削除に使用されますか? 


| config.deployments.create .15+| Google Cloud Infrastructure Manager を使用してCloud Volumes ONTAP仮想マシン インスタンスをデプロイします。 | はい | いいえ | いいえ 


| config.deployments.delete | いいえ | いいえ | はい 


| config.deployments.deleteState | いいえ | いいえ | はい 


| config.deployments.get | いいえ | はい | はい 


| config.deployments.getLock | いいえ | はい | いいえ 


| config.deployments.getState | いいえ | はい | いいえ 


| config.deployments.list | いいえ | はい | いいえ 


| config.deployments.lock | いいえ | はい | いいえ 


| config.deployments.update | いいえ | はい | いいえ 


| config.deployments.updateState | いいえ | はい | いいえ 


| config.operations.get | いいえ | はい | いいえ 


| config.previews.get | いいえ | はい | いいえ 


| config.previews.list | いいえ | はい | いいえ 


| config.resources.list | いいえ | はい | いいえ 


| config.revisions.get | いいえ | はい | いいえ 


| コンピューティングディスクの作成 .8+| Cloud Volumes ONTAP システムでディスクを作成および管理します。 | はい | はい | いいえ 


| compute.disks.createSnapshot | いいえ | はい | いいえ 


| 計算ディスク削除 | いいえ | はい | はい 


| compute.disks.get | いいえ | はい | いいえ 


| 計算ディスクリスト | はい | はい | いいえ 


| compute.disks.setLabels | はい | はい | いいえ 


| compute.disks.update | いいえ | はい | いいえ 


| 計算ディスク使用 | いいえ | はい | いいえ 


| compute.firewalls.create .4+| Cloud Volumes ONTAPのファイアウォール ルールを作成します。 | はい | いいえ | いいえ 


| compute.firewalls.delete | いいえ | はい | はい 


| compute.firewalls.get | はい | はい | いいえ 


| compute.firewalls.list | はい | はい | いいえ 


| compute.forwardingRules.create | バックエンド サービスへのトラフィック ルーティング用の転送ルールを作成します。 | いいえ | はい | いいえ 


| compute.forwardingRules.delete | 既存の転送ルールを削除します。 | いいえ | はい | いいえ 


| compute.forwardingRules.get | 既存の転送ルールの詳細を取得します。 | いいえ | はい | いいえ 


| compute.forwardingRules.setLabels | 組織の転送ルールのラベルを設定または更新します。 | いいえ | はい | いいえ 


| compute.forwardingRules.update | トラフィック管理のために既存の転送ルールを更新します。 | いいえ | はい | いいえ 


| compute.globalOperations.get | 操作のステータスを取得します。 | はい | はい | いいえ 


| compute.healthChecks.create .4+| バックエンド サービスの健全性を監視するためにヘルス チェックを作成および管理します。 | いいえ | はい | いいえ 


| compute.healthChecks.delete | いいえ | はい | いいえ 


| compute.healthChecks.get | いいえ | はい | いいえ 


| compute.healthChecks.useReadOnly | いいえ | はい | いいえ 


| 計算画像取得 .4+| VM インスタンスのイメージを取得します。 | はい | いいえ | いいえ 


| compute.images.getFromFamily | はい | いいえ | いいえ 


| 計算画像リスト | はい | いいえ | いいえ 


| compute.images.useReadOnly | はい | いいえ | いいえ 


| compute.instances.attachDisk .2+| Cloud Volumes ONTAPにディスクを接続および切断します。 | はい | はい | いいえ 


| compute.instances.detachDisk | いいえ | はい | はい 


| コンピューティングインスタンスの作成 .2+| Cloud Volumes ONTAP VMインスタンスを作成および削除します。 | はい | いいえ | いいえ 


| コンピューティングインスタンスの削除 | いいえ | いいえ | はい 


| コンピューティングインスタンスの取得 | VM インスタンスを一覧表示します。 | はい | はい | いいえ 


| compute.instances.getSerialPortOutput | コンソールログを取得します。 | はい | はい | いいえ 


| 計算インスタンスリスト | ゾーン内のインスタンスのリストを取得します。 | はい | はい | いいえ 


| compute.instances.setDeletionProtection | インスタンスに削除保護を設定します。 | はい | いいえ | いいえ 


| compute.instances.setLabels | ラベルを追加します。 | はい | いいえ | いいえ 


| compute.instances.setMachineType .2+| Cloud Volumes ONTAPのマシンタイプを変更します。 | はい | はい | いいえ 


| compute.instances.setMinCpuPlatform | はい | はい | いいえ 


| compute.instances.setMetadata | メタデータを追加します。 | はい | はい | いいえ 


| compute.instances.setTags | ファイアウォール ルールのタグを追加します。 | はい | はい | いいえ 


| コンピューティングインスタンスの開始 .3+| Cloud Volumes ONTAP を起動および停止します。 | はい | はい | いいえ 


| コンピューティングインスタンスの停止 | はい | はい | いいえ 


| compute.instances.updateDisplayDevice | はい | はい | いいえ 


| コンピューティングインスタンスの使用 | 仮想マシン インスタンス (開始、停止、接続操作) を使用します。 | いいえ | はい | いいえ 


| compute.machineTypes.get | クォータを確認するためのコア数を取得します。 | はい | いいえ | いいえ 


| compute.projects.get | 複数のプロジェクトをサポートします。 | はい | いいえ | いいえ 


| compute.resourcePolicies.create .3+| 自動リソース管理のためのリソース ポリシーを作成および管理します。 | いいえ | はい | いいえ 


| compute.resourcePolicies.delete | いいえ | はい | いいえ 


| compute.resourcePolicies.get | いいえ | はい | いいえ 


| 計算スナップショット作成 .5+| 永続ディスクのスナップショットを作成および管理します。 | はい | はい | いいえ 


| 計算スナップショットの削除 | いいえ | はい | はい 


| compute.snapshots.get | いいえ | はい | いいえ 


| 計算スナップショットリスト | いいえ | はい | いいえ 


| compute.snapshots.setLabels | はい | はい | いいえ 


| compute.networks.get .9+| 新しいCloud Volumes ONTAP仮想マシンインスタンスを作成するために必要なネットワーク情報を取得します。 | はい | はい | いいえ 


| compute.networks.list | はい | はい | いいえ 


| compute.regions.get | はい | はい | いいえ 


| compute.regions.list | はい | はい | いいえ 


| compute.subnetworks.get | はい | はい | いいえ 


| compute.subnetworks.list | はい | はい | いいえ 


| compute.zoneOperations.get | はい | はい | いいえ 


| compute.zones.get | はい | はい | いいえ 


| compute.zones.list | はい | はい | いいえ 


| デプロイメントマネージャー.複合タイプ.get .16+| Google Cloud Deployment Manager を使用してCloud Volumes ONTAP仮想マシン インスタンスをデプロイします。 | はい | いいえ | いいえ 


| デプロイメントマネージャー.複合タイプ.リスト | はい | いいえ | いいえ 


| デプロイメントマネージャー.デプロイメント.作成 | はい | いいえ | いいえ 


| デプロイメントマネージャー.デプロイメント.削除 | はい | いいえ | いいえ 


| デプロイメントマネージャー.デプロイメント.取得 | はい | いいえ | いいえ 


| デプロイメントマネージャー.デプロイメントリスト | はい | いいえ | いいえ 


| デプロイメントマネージャーマニフェストの取得 | はい | いいえ | いいえ 


| デプロイメントマネージャーマニフェストリスト | はい | いいえ | いいえ 


| デプロイメントマネージャー.操作.取得 | はい | いいえ | いいえ 


| デプロイメントマネージャー操作リスト | はい | いいえ | いいえ 


| デプロイメントマネージャー.リソース.取得 | はい | いいえ | いいえ 


| デプロイメントマネージャー.リソース.リスト | はい | いいえ | いいえ 


| デプロイメントマネージャー.typeProviders.get | はい | いいえ | いいえ 


| デプロイメントマネージャー.typeProviders.リスト | はい | いいえ | いいえ 


| デプロイメントマネージャータイプ取得 | はい | いいえ | いいえ 


| デプロイメントマネージャータイプリスト | はい | いいえ | いいえ 


| ログ記録.logEntries.リスト .2+| スタック ログ ドライブを取得します。 | はい | はい | いいえ 


| ログ記録.privateLogEntries.リスト | はい | はい | いいえ 


| ログ記録.logEntries.create .2+| 監視、デバッグ、監査のためにログエントリを作成してルーティングします。 | はい | はい | いいえ 


| ログ記録.logEntries.ルート | はい | はい | いいえ 


| リソースマネージャー.プロジェクト.取得 | 複数のプロジェクトをサポートします。 | はい | はい | いいえ 


| ストレージバケットの作成 .5+| データ階層化用の Google Cloud Storage バケットを作成および管理します。 | はい | はい | いいえ 


| ストレージバケットの削除 | いいえ | はい | はい 


| ストレージバケットの取得 | いいえ | はい | いいえ 


| ストレージバケットリスト | いいえ | はい | いいえ 


| ストレージ.バケット.更新 | いいえ | はい | いいえ 


| cloudkms.cryptoKeyVersions.useToEncrypt .5+| Cloud Volumes ONTAPで Cloud Key Management Service の顧客管理暗号化キーを使用する。 | はい | はい | いいえ 


| cloudkms.cryptoKeys.get | はい | はい | いいえ 


| cloudkms.cryptoKeys.リスト | はい | はい | いいえ 


| cloudkms.keyRings.リスト | はい | はい | いいえ 


| cloudbuild.builds.get | はい | いいえ | いいえ 


| cloudbuild.workerpools.get | Infrastructure Manager を使用したプライベートモードの導入時および Cloud Volumes ONTAP システムの変換時にワーカープール情報にアクセスするため。 | はい | はい | はい 


| cloudbuild.workerpools.list | Infrastructure Manager を使用した Cloud Volumes ONTAP システムのプライベートモード展開中にワーカープール情報を一覧表示するには。 | はい | いいえ | いいえ 


| compute.instances.setServiceAccount .6+| Cloud Volumes ONTAPインスタンスにサービス アカウントを設定します。このサービス アカウントは、Google Cloud Storage バケットへのデータ階層化の権限を付与します。 | はい | はい | いいえ 


| iam.serviceAccounts.actAs | はい | いいえ | いいえ 


| iam.serviceAccounts.create | はい | いいえ | いいえ 


| iam.serviceAccounts.getIamPolicy | はい | はい | いいえ 


| iam.serviceAccounts.list | はい | はい | いいえ 


| iam.serviceAccountKeys.create | はい | いいえ | いいえ 


| ストレージオブジェクトの作成 .4+| Google Cloud Storage バケット内のオブジェクト (ファイル) を作成および管理します。 | はい | はい | いいえ 


| ストレージオブジェクトの削除 | いいえ | いいえ | はい 


| ストレージオブジェクト取得 | はい | はい | いいえ 


| ストレージオブジェクトリスト | はい | はい | いいえ 


| 計算アドレスリスト | HA ペアを展開するときにリージョン内のアドレスを取得します。 | はい | いいえ | いいえ 


| compute.addresses.createInternal | リソース割り当てのために、VPC ネットワーク内に内部 IP アドレスを作成します。 | いいえ | はい | いいえ 


| compute.addresses.deleteInternal | リソースのクリーンアップのために内部 IP アドレスを削除します。 | いいえ | はい | いいえ 


| compute.addresses.setLabels | アドレス リソースのラベルを更新します。 | いいえ | はい | いいえ 


| compute.addresses.useInternal | ネットワーク通信には内部 IP アドレスを使用します。 | いいえ | はい | いいえ 


| compute.backendServices.create | HA ペアでトラフィックを分散するためのバックエンド サービスを設定します。 | はい | いいえ | いいえ 


| compute.regionBackendServices.create .6+| トラフィック ルーティング用のバックエンド サービスを作成および管理します。 | はい | いいえ | いいえ 


| compute.regionBackendServices.delete | いいえ | はい | いいえ 


| compute.regionBackendServices.get | はい | いいえ | いいえ 


| compute.regionBackendServices.更新 | はい | はい | いいえ 


| compute.regionBackendServices.リスト | はい | いいえ | いいえ 


| compute.regionBackendServices.use | いいえ | はい | いいえ 


| compute.networks.updatePolicy | HA ペアの VPC とサブネットにファイアウォール ルールを適用します。 | はい | いいえ | いいえ 


| compute.instanceGroups.get .7+| Cloud Volumes ONTAP HA ペアでストレージ VM を作成および管理します。 | はい | はい | いいえ 


| 計算アドレス取得 | はい | はい | いいえ 


| compute.instances.updateNetworkInterface | はい | はい | いいえ 


| compute.instanceGroups.create | いいえ | はい | いいえ 


| compute.instanceGroups.delete | いいえ | はい | いいえ 


| compute.instanceGroups.update | いいえ | はい | いいえ 


| compute.instanceGroups.use | いいえ | はい | いいえ 


| 監視.timeSeries.リスト .2+| Google Cloud Storage バケットに関する情報を検出します。 | はい | はい | いいえ 


| ストレージ.バケット.getIamPolicy | はい | はい | いいえ 
|===
====


=== NetApp Backup and Recoveryに使用される権限

コンソール エージェントは、カスタムロールの権限を使用して、Google Cloud ネットワーク内のNetApp Backup and Recovery のリソースとプロセスを管理します。次のセクションでは、エージェントがこれらの権限をどのように使用するかについて説明します。

.NetApp Backup and Recoveryの権限の表示
[%collapsible]
====
[cols="5*"]
|===


| アクション | 目的 | 展開に使用されますか? | 日常業務に使用されますか? | 削除に使用されますか? 


 a| 
* cloudkms.cryptoKeys.get
* cloudkms.cryptoKeys.getIamPolicy
* cloudkms.cryptoKeys.リスト
* cloudkms.cryptoKeys.setIamPolicy
* cloudkms.keyRings.get
* cloudkms.keyRings.getIamPolicy
* cloudkms.keyRings.リスト
* cloudkms.keyRings.setIamPolicy

| デフォルトの Google 管理暗号化キーを使用する代わりに、 NetApp Backup and Recoveryアクティベーション ウィザードで独自の顧客管理キーを選択します。 | はい | はい | いいえ 
|===
====


=== NetApp Data Classificationに使用される権限

コンソール エージェントは、カスタムロールの権限を使用して、Google Cloud ネットワーク内のNetApp Data Classification のリソースとプロセスを管理します。次のセクションでは、エージェントがこれらの権限をどのように使用するかについて説明します。

.NetApp Data Classificationの表示権限
[%collapsible]
====
[cols="5*"]
|===


| アクション | 目的 | 展開に使用されますか? | 日常業務に使用されますか? | 削除に使用されますか? 


 a| 
* 計算サブネットワーク使用
* compute.subnetworks.useExternalIp
* compute.instances.addAccessConfig

| NetApp Data Classification を有効にします。 | はい | いいえ | いいえ 
|===
====


== 変更ログ

追加された権限と削除された権限は以下に記載されています。



=== 2026年4月13日

 `compute.disks.update`権限が追加され、Cloud Volumes ONTAP システムの Hyperdisk Balanced アグリゲートまたはディスクの IOPS およびスループット パラメータを更新できるようになりました。



=== 2026年2月26日

 `cloudbuild.workerpools.get`および `cloudbuild.workerpools.list`の権限は、Google CloudでのCloud Volumes ONTAPのプライベートモード導入におけるInfrastructure Managerをサポートするために追加されました。



=== 2026年2月9日

 `compute.forwardingRules.update`権限は、Google Cloud での Cloud Volumes ONTAP 導入において Infrastructure Manager をサポートするために追加されました。



=== 2025年12月8日

NetApp は、Google Cloud でコンソール エージェントをデプロイおよび実行するために、Google Cloud Deployment Manager から Google Cloud Infrastructure Manager（IM）に移行しています。この変更をサポートするために、次の権限が追加されました。

エージェントをデプロイする Google Cloud ユーザーには、次の追加権限が必要です。

* ストレージバケットの作成
* ストレージバケットの取得
* ストレージオブジェクトの作成
* ストレージフォルダの作成
* ストレージオブジェクトリスト
* iam.serviceAccount.actAs
* config.deployments.create
* config.operations.get


日常業務に使用する Google Cloud のサービス アカウントには、次の追加権限が必要です。

* cloudbuild.接続リスト
* cloudbuild.repositories.accessReadToken
* cloudbuild.リポジトリリスト
* cloudquotas.quotas.get
* config.artifacts.import
* config.deployments.deleteState
* config.deployments.getLock
* config.deployments.getState
* config.deployments.updateState
* config.previews.upload
* config.revisions.getState
* ログ記録.logEntries.create
* ストレージオブジェクトの作成
* ストレージオブジェクトの削除
* ストレージオブジェクトの更新
* iam.serviceAccounts.get


Cloud Volumes ONTAP をデプロイするには、次の追加の権限が必要です。

* cloudbuild.builds.get
* config.deployments.delete
* config.deployments.deleteState
* config.deployments.get
* config.deployments.getState
* config.deployments.list
* config.deployments.update
* config.deployments.updateState
* config.previews.get
* config.previews.list
* config.revisions.get
* config.resources.list
* iam.serviceAccountKeys.create
* iam.serviceAccounts.create


Cloud Volumes ONTAPの日常的な運用に使用するサービス アカウントには、次の追加の権限が必要です。

* compute.addresses.createInternal
* compute.addresses.deleteInternal
* compute.addresses.setLabels
* compute.addresses.useInternal
* compute.forwardingRules.create
* compute.forwardingRules.delete
* compute.forwardingRules.get
* compute.forwardingRules.setLabels
* compute.healthChecks.create
* compute.healthChecks.delete
* compute.healthChecks.get
* compute.healthChecks.useReadOnly
* compute.instanceGroups.create
* compute.instanceGroups.delete
* compute.instanceGroups.update
* compute.instanceGroups.use
* コンピューティングインスタンスの使用
* compute.regionBackendServices.delete
* compute.regionBackendServices.更新
* compute.regionBackendServices.use
* compute.resourcePolicies.create
* compute.resourcePolicies.delete
* compute.resourcePolicies.get
* ログ記録.logEntries.ルート
* config.deployments.create
* config.deployments.delete
* config.deployments.get
* config.deployments.update
* config.revisions.get
* config.deployments.lock
* config.operations.get




=== 2025年11月26日

権限は使用法を明確にするために更新されていますが、権限の追加や削除は行われていません。各権限がデプロイメント、日常的な操作、または削除のいずれに使用されるかを示す 3 つの列が追加されます。これとは別に、 NetApp Data ClassificationおよびNetApp Backup and Recoveryでの使用に基づいて、いくつかの権限が分離されています。



=== 2023年2月6日

このポリシーに次の権限が追加されました:

* compute.instances.updateNetworkInterface


この権限はCloud Volumes ONTAPに必要です。



=== 2023/01/27

このポリシーには次の権限が追加されました:

* cloudkms.cryptoKeys.getIamPolicy
* cloudkms.cryptoKeys.setIamPolicy
* cloudkms.keyRings.get
* cloudkms.keyRings.getIamPolicy
* cloudkms.keyRings.setIamPolicy


これらの権限は、NetApp Backup and Recoveryに必要です。
