---
sidebar: sidebar 
permalink: reference-networking-saas-console.html 
keywords: networking, urls, endpoints, web browser, console, network, set up networking, bluexp 
summary: NetApp Console、 NetApp Consoleエージェント、およびNetAppデータ サービスには、アウトバウンド インターネット アクセスと、必要なエンドポイントに接続する機能が必要です。 
---
= NetApp Console のネットワークアクセス
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Console、 NetApp Consoleエージェント、およびNetAppデータ サービスには、アウトバウンド インターネット アクセスと、必要なエンドポイントに接続する機能が必要です。

次のネットワーク アクセスを設定する必要があります。

* NetApp Consoleに SaaS (Software as a Service) としてアクセスするコンピュータ
* オンプレミスまたはクラウドにインストールするコンソール エージェント。コンソールエージェント。



NOTE: 4.0.0 では、 NetApp はコンソールとコンソール エージェントに必要なネットワーク エンドポイントを削減し、セキュリティを強化して導入を簡素化しました。重要なのは、バージョン 4.0.0 より前のすべてのデプロイメントが引き続き完全にサポートされることです。以前のエンドポイントは既存のエージェントで引き続き使用できますが、 NetApp、エージェントのアップグレードが成功したことを確認した後、ファイアウォール ルールを現在のエンドポイントに更新することを強くお勧めします。link:reference-networking-saas-console-previous.html["エンドポイント リストを更新する方法について説明します。"]



== NetApp Consoleおよびコンソールエージェントが接続するエンドポイント

導入する各エージェントとNetApp Consoleにアクセスする各コンピューターは、以下にリストされているエンドポイントに接続する必要があります。

クラウド プロバイダーに展開されているコンソール エージェントは、そのクラウド プロバイダーに対応するエンドポイントにアクセスできる必要があります。

[cols="2*"]
|===
| エンドポイント | 目的 


| \https://mysupport.netapp.com | ライセンス情報を取得し、AutoSupportメッセージをNetAppサポートに送信します。 


| \https://signin.b2c.netapp.com | NetAppサポート サイト (NSS) の資格情報を更新したり、 NetApp Consoleに新しい NSS 資格情報を追加したりします。 


| \https://support.netapp.com | ライセンス情報を取得し、AutoSupportメッセージをNetAppサポートに送信するとともに、Cloud Volumes ONTAPのソフトウェアアップデートを受信するため。 


| \https://api.bluexp.netapp.com \https://netapp-cloud-account.auth0.com \https://netapp-cloud-account.us.auth0.com \https://console.netapp.com \https://components.console.netapp.com \https://cdn.auth0.com | NetApp Console内で機能とサービスを提供します。 


 a| 
\https://bluexpinfraprod.eastus2.data.azurecr.io \https://bluexpinfraprod.azurecr.io
 a| 
コンソール エージェントのアップグレード用のイメージを取得します。

|===


== クラウドプロバイダーのエンドポイントがコンソールエージェントに接続しました

コンソール エージェントがクラウド プロバイダーに展開されている場合、追加のエンドポイントにアクセスできる必要があります。

コンソール エージェントをインストールする前に、クラウド プロバイダー ネットワーク エンドポイント アクセスを設定します。

* link:task-install-agent-aws-console.html#networking-aws-agent["コンソールエージェントの AWS ネットワークアクセスを設定する"]
* link:task-install-agent-azure-console.html#networking-azure-agent["コンソール エージェントの Azure ネットワーク アクセスを設定する"]
* link:task-install-agent-google-console-gcloud.html#networking-gcp-agent["コンソール エージェントの Google Cloud ネットワーク アクセスを設定する"]




== コンソールエージェントが接続するデータサービスエンドポイント

一部のNetAppデータ サービスとCloud Volumes ONTAP、エージェントに追加のアウトバウンド インターネット アクセスが必要です。



=== Cloud Volumes ONTAPのエンドポイント

* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-aws.html#outbound-internet-access-for-cloud-volumes-ontap-nodes["AWS のCloud Volumes ONTAPのエンドポイント"]
* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-azure.html["Azure のCloud Volumes ONTAPのエンドポイント"]
* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-gcp.html#outbound-internet-access["Google Cloud のCloud Volumes ONTAPのエンドポイント"]




=== ワークロードのエンドポイント

コンソール エージェントは、 NetAppワークロードの次のエンドポイントにアクセスできる必要があります。

[cols="2*"]
|===
| エンドポイント | 目的 


 a| 
\https://api.workloads.netapp.com
 a| 
Webベースのコンソールは、このエンドポイントに接続して Workload Factory API と対話し、FSx for ONTAPベースのワークロードを管理および操作します。

|===