---
sidebar: sidebar 
permalink: reference-agent-maint-console-config-checker.html 
keywords: transparent proxy, connector certificate, agent maintenance console, proxy configuration, connector proxy. agent proxy 
summary: コンソール エージェント メンテナンス コンソールを使用して、透過プロキシ サーバーを使用するようにコンソール エージェントを構成できます。 
---
= NetApp Console のメンテナンスコンソールを使用したコンソールエージェントの検証
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
コンソール エージェント メンテナンス コンソールを使用して、コンソール エージェントのインストールと構成を検証できます。



== エージェントメンテナンスコンソールにアクセスする

コンソール エージェント ホストからメンテナンス コンソールにアクセスできます。次のディレクトリに移動します。

[source, cli]
----
/opt/application/netapp/service-manager-2/agent-maint-console
----


== 構成チェッカーの検証

その `config-checker validate`コマンドを使用すると、コンソール エージェントの構成を検証できます。



=== パラメータ

`--services <comma-separated list of services to validate>` - *必須* - 

[role="quick-margin-para"]
検証するサービスを1つ以上選択してください。有効なサービス名は次のとおりです：

*`PLATFORM`これは、必要なNetApp Consoleエンドポイントへのネットワーク接続を検証するとともに、NetApp Consoleエージェントに必要なポートが開いているかどうかも検証します。

`--validationTypes <comma-separated list validation types to run>` --*REQUIRED*-- 実行する検証タイプを1つ以上選択してください。有効な検証タイプは次のとおりです：

* `NETWORK`これは、必要な Console エンドポイントへのネットワーク接続を検証します。
* `HARDWARE`これは、エージェントホストが NetApp Console エージェントの最小ハードウェア要件を満たしていることを検証するものです。
+

NOTE: インストール中、NetAppは、エージェントホストに、ディスク全体の空き容量の少なくとも80パーセントがあることを確認します。これには、 `/opt`に48 GB、 `/var`に32 GBが含まれます（合計80 GB）。インストール後、ディスク全体の少なくとも20パーセントが利用可能である必要があり、これには、 `/opt`に12 GB、 `/var`に8 GBが含まれます（合計20 GB）。



`--proxy <url>`--*オプション*--

[role="quick-margin-para"]
検証に使用するプロキシ サーバーの URL を指定します。エージェントがプロキシ サーバーを使用するように構成されている場合に必要です。

`--certs <paths>`--*オプション*--

[role="quick-margin-para"]
検証に使用する 1 つ以上の証明書ファイルへのパスを指定します。証明書ファイルは PEM 形式である必要があります。複数のパスはコンマで区切ります。エージェントがカスタム証明書を使用する場合、このパラメータは必須です。



=== 構成チェッカーの検証例

以下の例には、ネットワーク接続、必要なポート、ハードウェア要件の検証と、プロキシ サーバおよびカスタム証明書のさまざまな組み合わせの使用が含まれます。

.ネットワーク接続性およびハードウェア要件の検証：
[source, cli]
----
./agent-maint-console config-checker validate --services PLATFORM --validationTypes NETWORK,HARDWARE
----
.エージェントにプロキシ サーバーが使用される場合の検証:
[source, cli]
----
./agent-maint-console config-checker validate --services PLATFORM --validationTypes NETWORK,HARDWARE --proxy http://proxy.company.com:8080
----
.エージェントに証明書が使用される場合の検証:
[source, cli]
----
./agent-maint-console config-checker validate --services PLATFORM --validationTypes NETWORK,HARDWARE --certs /path/to/cert1.pem,/path/to/cert2.pem
----


=== 任意のコマンドのヘルプを表示する

コマンドのヘルプを表示するには、 `--help`コマンドに。たとえば、 `proxy add`コマンドを実行するには、次のコマンドを使用します。

[source, cli]
----
./agent-maint-console proxy add --help
----