---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, active directory, ad, iscsi, key managers, ip address, govcloud, Cloud Volumes ONTAP, days, running,  imdsv2, https tokens, Console agent 
summary: 今回のリリースでサポートされていない、または今回のリリースでは正常に機能しないプラットフォーム、デバイス、機能が記載されています。これらの制限事項をよく確認してください。 
---
= NetApp Consoleの既知の制限
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
今回のリリースでサポートされていない、または今回のリリースでは正常に機能しないプラットフォーム、デバイス、機能が記載されています。これらの制限事項をよく確認してください。

これらの制限は、NetApp Consoleと管理のセットアップに固有のものです：エージェント、サービスとしてのソフトウェア（SaaS）プラットフォームなど。



== コンソールエージェントの制限



=== 172番台のIPアドレスとの競合の可能性

NetApp Consoleは、172.17.0.0/16 および 172.18.0.0/16 の範囲の IP アドレスを持つ 2 つのインターフェースを持つエージェントを展開します。

ネットワークにこれらのいずれかの範囲で構成されたサブネットがある場合、コンソールからの接続エラーが発生する可能性があります。たとえば、コンソールでオンプレミスのONTAPクラスターを検出できない場合があります。

ナレッジベースの記事を参照link:https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Manager/Cloud_Manager_shows_inactive_as_Connector_IP_range_in_172.x.x.x_conflict_with_docker_network["エージェントIPが既存のネットワークと競合する"]エージェントのインターフェースの IP アドレスを変更する方法については、こちらをご覧ください。



=== SSL 復号化は Cloud Volumes ONTAP でのみサポートされます

透過プロキシ サーバは、Cloud Volumes ONTAP に関連付けられたエージェントでのみサポートされます。他のNetAppデータサービスで使用されているエージェントでは、透過プロキシを使用できません。NetAppデータサービスを Cloud Volumes ONTAP と併用する場合は、透過プロキシ サーバを使用できる Cloud Volumes ONTAP 専用のエージェントを作成してください。

セキュリティを強化するために、link:task-installing-https-cert.html["証明機関（CA）によって署名されたHTTPS証明書をインストールする"] 。



=== ローカルUIを読み込むときに空白ページが表示される

エージェント上で実行されている Web ベースのコンソールをロードすると、インターフェイスが表示されず、空白のページが表示される場合があります。

この問題はキャッシュの問題に関連しています。回避策としては、シークレット モードまたはプライベート Web ブラウザ セッションを使用します。



=== 共有Linuxホストはサポートされていません

エージェントは、他のアプリケーションと共有されている VM ではサポートされません。  VM はエージェント ソフトウェア専用にする必要があります。



=== サードパーティのエージェントと拡張機能

エージェント VM では、サードパーティ エージェントまたは VM 拡張機能はサポートされません。
