---
sidebar: sidebar 
permalink: reference-networking-saas-console-previous.html 
keywords: networking, urls, endpoints, web browser, console, network, set up networking, bluexp 
summary: ログインして Web ベースのコンソールを使用すると、開始したアクションを完了するために複数のエンドポイントに接続します。  NetApp Consoleにアクセスするコンピューターは、これらのエンドポイントに接続する必要があります。 
---
= 3.9.55 以前に必要なネットワーク アクセス ポイント
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
このトピックでは、 NetApp Console4.0.0 リリースより前のバージョンのNetApp Consoleコンソール標準モード、 NetApp Consoleエージェント、およびNetAppデータ サービスのアウトバウンド インターネット アクセス、および必要なエンドポイントに接続する機能に必要なネットワーク アクセスについて詳しく説明します。コンソールとインストールするエージェントに、機能プロパティへの適切なネットワーク アクセスがあることを確認する必要があります。

NetApp Consoleに SaaS (Software as a Service) としてアクセスするコンピューターと、オンプレミスまたはクラウドにインストールするコンソール エージェントのネットワーク アクセスを設定する必要があります。  Cloud Volumes ONTAPなどの特定のNetAppデータ サービスには追加のエンドポイントが必要になる場合もあります。



== エンドポイント リストを 4.0.0 以降の改訂リストに更新します。

バージョン 4.0.0 以降、コンソール エージェントに必要なエンドポイントが少なくなります。  4.0.0 より前の既存のデプロイメントは引き続きサポートされます。  4.0.0 以降にアップグレードした後、都合の良いときに古いエンドポイントを許可リストから削除できます。

NetApp、改訂されたエンドポイント リストを使用するようにファイアウォール ルールを更新することをお勧めします。改訂されたリストは小さくなったため、より安全になり、管理も容易になりました。

レビューlink:reference-networking-saas-console.html["4.0.0以降でサポートされているエンドポイント"]

.手順
. エンドポイントをホワイトリストに登録するlink:reference-networking-saas-console.html["4.0.0 以降でサポートされているエンドポイント"]。
. 次のコマンドを実行して、各エージェントのサービス マネージャー 2 サービスを再起動します。
+
[source, cli]
----
systemctl restart netapp-service-manager.service
----
. 次のコマンドを実行し、エージェントのステータスが _active(running)_ と表示されていることを確認します: _
+
[source, cli]
----
systemctl status netapp-service-manager.service
----
. 許可リストから古いエンドポイントを削除します。




== NetApp Consoleが接続するエンドポイント

NetApp Consoleにアクセスする各コンピューターは、以下にリストされているエンドポイントに接続されている必要があります。

システムは、次の 2 つのシナリオでこれらのエンドポイントに接続します。

* アクセスしているコンピュータから https://console.netapp.com["NetApp Console"^]サービスとしてのソフトウェア (SaaS) として。
* エージェント ホストに直接アクセスするコンピュータから、ログインして設定するか、エージェント ホストからコンソールにアクセスします。


[cols="2*"]
|===
| エンドポイント | 目的 


| \https://support.netapp.com \https://mysupport.netapp.com | ライセンス情報を取得し、 AutoSupportメッセージをNetAppサポートに送信します。 


| \https://\*.api.bluexp.netapp.com \https://api.bluexp.netapp.com \https://*.cloudmanager.cloud.netapp.com \https://cloudmanager.cloud.netapp.com \https://netapp-cloud-account.auth0.com \https://netapp-cloud-account.us.auth0.com | NetApp Console内で機能とサービスを提供します。 


 a| 
次の 2 つのエンドポイント セットから選択します。

* オプション1（推奨）
+
\https://bluexpinfraprod.eastus2.data.azurecr.io \https://bluexpinfraprod.azurecr.io

* オプション2
+
\https://*.blob.core.windows.net \https://cloudmanagerinfraprod.azurecr.io


 a| 
コンソール エージェントのアップグレード用のイメージを取得します。

NetApp、ランサムウェア耐性またはバックアップとリカバリを使用していない限り、より安全なオプション 1 のエンドポイントをファイアウォールで許可し、オプション 2 のエンドポイントを禁止することを推奨しています。これらのエンドポイントについては、次の点に注意してください。

* オプション 1 エンドポイントは 3.9.47 以降でサポートされます。  3.9.47 より前のリリースでは下位互換性がサポートされていません。
* コンソール エージェントは、まずオプション 2 のエンドポイントとの接続を開始します。これらのエンドポイントにアクセスできない場合は、オプション 1 のエンドポイントに自動的に接続します。
* コンソール エージェントをNetApp Backup and Recoveryまたは Ransomware Resilience と併用する場合、システムはオプション 1 のエンドポイントをサポートしません。オプション 2 のエンドポイントを許可し、オプション 1 を禁止します。


|===


== コンソールエージェントが接続するエンドポイント

コンソール エージェントをオンプレミスまたはクラウドにインストールし、エンドポイントに接続してコンソールによって開始されたアクションを完了します。

コンソール エージェントは、 NetApp Consoleと同じエンドポイントにアクセスできる必要があります。また、エージェントをクラウド プロバイダーに導入する場合は追加のエンドポイントにもアクセスできる必要があります。



=== AWS のエージェントエンドポイント

これらのエンドポイントは、4.0.0 より前のコンソール エージェントに適用されます。

[cols="2*"]
|===
| エンドポイント | 目的 


| AWS サービス (amazonaws.com): CloudFormation Elastic Compute Cloud (EC2) Identity and Access Management (IAM) Key Management Service (KMS) Security Token Service (STS) Simple Storage Service (S3) | AWS 内のリソースを管理します。正確なエンドポイントは、使用している AWS リージョンによって異なります。ライセンス情報を取得し、 AutoSupportメッセージをNetAppサポートに送信する方法については、AWS のドキュメントを参照してください。 


| \https://support.netapp.com \https://mysupport.netapp.com | ライセンス情報を取得し、 AutoSupportメッセージをNetAppサポートに送信します。 


 a| 
次の 2 つのエンドポイント セットから選択します。

* オプション1（推奨）
+
\https://bluexpinfraprod.eastus2.data.azurecr.io \https://bluexpinfraprod.azurecr.io

* オプション2
+
\https://*.blob.core.windows.net \https://cloudmanagerinfraprod.azurecr.io


 a| 
コンソール エージェントのアップグレード用のイメージを取得します。

NetApp、ランサムウェア耐性またはバックアップとリカバリを使用していない限り、より安全なオプション 1 のエンドポイントをファイアウォールで許可し、オプション 2 のエンドポイントを禁止することを推奨しています。これらのエンドポイントについては、次の点に注意してください。

* オプション 1 エンドポイントは 3.9.47 以降でサポートされます。  3.9.47 より前のリリースでは下位互換性がサポートされていません。
* コンソール エージェントは、まずオプション 2 のエンドポイントとの接続を開始します。これらのエンドポイントにアクセスできない場合は、オプション 1 のエンドポイントに自動的に接続します。
* コンソール エージェントをNetApp Backup and Recoveryまたは Ransomware Resilience と併用する場合、システムはオプション 1 のエンドポイントをサポートしません。オプション 2 のエンドポイントを許可し、オプション 1 を禁止します。


|===


=== Azureのエージェントエンドポイント

これらのエンドポイントは、4.0.0 より前のコンソール エージェントに適用されます。

[cols="2*"]
|===
| エンドポイント | 目的 


| \https://management.azure.com \https://login.microsoftonline.com \https://blob.core.windows.net \https://core.windows.net | Azure パブリック リージョン内のリソースを管理します。 


| \https://management.chinacloudapi.cn \https://login.chinacloudapi.cn \https://blob.core.chinacloudapi.cn \https://core.chinacloudapi.cn | Azure China リージョンのリソースを管理します。 


| \https://support.netapp.com \https://mysupport.netapp.com | ライセンス情報を取得し、 AutoSupportメッセージをNetAppサポートに送信します。 


 a| 
次の 2 つのエンドポイント セットから選択します。

* オプション1（推奨）
+
\https://bluexpinfraprod.eastus2.data.azurecr.io \https://bluexpinfraprod.azurecr.io

* オプション2
+
\https://*.blob.core.windows.net \https://cloudmanagerinfraprod.azurecr.io


 a| 
コンソール エージェントのアップグレード用のイメージを取得します。

NetApp、ランサムウェア耐性またはバックアップとリカバリを使用していない限り、より安全なオプション 1 のエンドポイントをファイアウォールで許可し、オプション 2 のエンドポイントを禁止することを推奨しています。これらのエンドポイントについては、次の点に注意してください。

* オプション 1 エンドポイントは 3.9.47 以降でサポートされます。  3.9.47 より前のリリースでは下位互換性がサポートされていません。
* コンソール エージェントは、まずオプション 2 のエンドポイントとの接続を開始します。これらのエンドポイントにアクセスできない場合は、オプション 1 のエンドポイントに自動的に接続します。
* コンソール エージェントをNetApp Backup and Recoveryまたは Ransomware Resilience と併用する場合、システムはオプション 1 のエンドポイントをサポートしません。オプション 2 のエンドポイントを許可し、オプション 1 を禁止します。


|===


=== Google Cloud のエージェント エンドポイント

これらのエンドポイントは、4.0.0 より前のコンソール エージェントに適用されます。

[cols="2*"]
|===
| エンドポイント | 目的 


| \https://www.googleapis.com/compute/v1/ \https://compute.googleapis.com/compute/v1 \https://cloudresourcemanager.googleapis.com/v1/projects \https://www.googleapis.com/compute/beta \https://storage.googleapis.com/storage/v1 \https://www.googleapis.com/storage/v1 \https://iam.googleapis.com/v1 \https://cloudkms.googleapis.com/v1 \https://www.googleapis.com/deploymentmanager/v2/project | Google Cloud 内のリソースを管理します。 


| \https://support.netapp.com \https://mysupport.netapp.com | ライセンス情報を取得し、 AutoSupportメッセージをNetAppサポートに送信します。 


 a| 
次の 2 つのエンドポイント セットから選択します。

* オプション1（推奨）
+
\https://bluexpinfraprod.eastus2.data.azurecr.io \https://bluexpinfraprod.azurecr.io

* オプション2
+
\https://*.blob.core.windows.net \https://cloudmanagerinfraprod.azurecr.io


 a| 
コンソール エージェントのアップグレード用のイメージを取得します。

NetApp、より安全なオプション 1 のエンドポイントをファイアウォールで許可し、オプション 2 のエンドポイントを禁止することを推奨しています。これらのエンドポイントについては、次の点に注意してください。

* コンソール エージェントの 3.9.47 リリース以降、システムはオプション 1 にリストされているエンドポイントをサポートします。コンソール エージェントの以前のリリースでは、下位互換性はサポートされていません。
* コンソール エージェントは、最初にオプション 2 のエンドポイントに接続します。これらのエンドポイントにアクセスできない場合は、オプション 1 のエンドポイントに自動的に接続します。
* コンソール エージェントをNetApp Backup and Recoveryまたは Ransomware Resilience と併用する場合、システムはオプション 1 のエンドポイントをサポートしません。オプション 2 のエンドポイントを許可し、オプション 1 を禁止します。


|===


== オンプレミスのエージェントエンドポイント
