---
sidebar: sidebar 
permalink: task-federation-adfs.html 
keywords: federation, active directory federation services, adfs, ad fs, single sign-on, microsoft, federate, federated connection, SSO, identity federation, identity management, corporate identity 
summary: 'Active Directory フェデレーション サービス (AD FS) と連携して、 NetApp Consoleのシングル サインオン (SSO) を有効にします。これにより、ユーザーは企業の資格情報を使用してログインできるようになります。' 
---
= NetApp Console と Active Directory フェデレーション サービスのフェデレーション
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Active Directory フェデレーション サービス (AD FS) をNetApp Consoleと連携させて、 NetApp Consoleのシングル サインオン (SSO) を有効にします。これにより、ユーザーは企業の資格情報を使用してコンソールにログインできるようになります。

.必要な役割
フェデレーションの作成と管理には、フェデレーション管理者ロールが必要です。フェデレーション ビューアは、フェデレーション ページを表示できます。link:reference-iam-predefined-roles.html["アクセス ロールの詳細について説明します。"]


NOTE: 企業の IdP またはNetAppサポート サイトと連携できます。  NetApp、両方ではなく、どちらか一方を選択することを推奨しています。

NetApp は、サービス プロバイダー開始 (SP開始) SSO のみをサポートします。まず、 NetApp Consoleをサービス プロバイダーとして信頼するように ID プロバイダーを構成します。次に、ID プロバイダーの構成を使用してコンソールで接続を作成します。

AD FSサーバーとのフェデレーションを設定することで、NetApp Consoleのシングルサインオン（SSO）を有効にできます。このプロセスでは、AD FSを構成してConsoleをサービスプロバイダーとして信頼し、次にNetApp Consoleで接続を作成します。

.開始する前に
* 管理者権限を持つ IdP アカウントが必要です。  IdP 管理者と調整して手順を完了してください。
* フェデレーションに使用するドメインを特定してください。ご自身のメールアドレスのドメイン、またはご自身が所有する別のドメインを使用できます。メールアドレスのドメインとは異なるドメインを使用する場合は、まずコンソールでドメインを認証する必要があります。手順については、link:task-federation-verify-domain.html["NetApp Consoleでドメインを確認する"]を参照してください。


.手順
. *管理 > IDとアクセス*を選択します。
. *Federation* ページを表示するには、*Federation* を選択します。
. *新しいフェデレーションの構成*を選択します。
. ドメインの詳細を入力してください:
+
.. 検証済みドメインを使用するか、メールドメインを使用するかを選択します。電子メール ドメインは、ログインしているアカウントに関連付けられているドメインです。
.. 構成するフェデレーションの名前を入力します。
.. 検証済みのドメインを選択する場合は、リストからドメインを選択します。


. *次へ*を選択します。
. 接続方法として、[*プロトコル*] を選択し、[*Active Directory フェデレーション サービス (AD FS)*] を選択します。
. *次へ*を選択します。
. AD FS サーバーに証明書利用者信頼を作成します。 PowerShell を使用することも、AD FS サーバー上で手動で構成することもできます。証明書利用者信頼を作成する方法の詳細については、AD FS のドキュメントを参照してください。
+
.. PowerShellを使用して次のスクリプトを実行し、信頼関係を作成します。
+
[source, powershell]
----
(new-object Net.WebClient -property @{Encoding = [Text.Encoding]::UTF8}).DownloadString("https://raw.github.com/auth0/AD FS-auth0/master/AD FS.ps1") | iex
AddRelyingParty "urn:auth0:netapp-cloud-account" "https://netapp-cloud-account.auth0.com/login/callback"
----
.. または、AD FS 管理コンソールで信頼を手動で作成することもできます。信頼を作成するときは、次のNetApp Consoleの値を使用します。
+
*** 信頼関係識別子を作成する際は、*YOUR_TENANT* の値を使用してください： `netapp-cloud-account`
*** *Enable support for the WS-Federation*を選択する場合は、*YOUR_AUTH0_DOMAIN*の値を使用します： `netapp-cloud-account.auth0.com`


.. 信頼を作成した後、AD FS サーバーからメタデータ URL をコピーするか、フェデレーション メタデータ ファイルをダウンロードします。コンソールで接続を完了するには、この URL またはファイルが必要になります。


+
NetApp、メタデータ URL を使用してNetApp Consoleが最新の AD FS 構成を自動的に取得できるようにすることをお勧めします。フェデレーション メタデータ ファイルをダウンロードした場合は、AD FS 構成に変更があるたびに、 NetApp Consoleで手動で更新する必要があります。

. コンソールに戻り、[次へ] を選択して接続を作成します。
. AD FS との接続を作成します。
+
.. 前の手順で AD FS サーバーからコピーした *AD FS URL* を入力するか、AD FS サーバーからダウンロードしたフェデレーション メタデータ ファイルをアップロードします。


. *接続を作成*を選択します。接続の作成には数秒かかる場合があります。
. *次へ*を選択します。
. 接続をテストするには、[*接続テスト*] を選択します。IdP サーバーのログイン ページに移動します。IdPのクレデンシャルを使用してログインします。ログイン後、コンソールに戻って接続を有効にします。
+

NOTE: コンソールを制限モードで使用する場合は、URL をシークレット ブラウザ ウィンドウまたは別のブラウザにコピーして IdP にログインします。

. コンソールで、[*次へ*] を選択して概要ページを確認します。
. 通知を設定します。
+
7日間または30日間からお選びください。システムは、有効期限切れの通知をメールで送信し、NetApp Consoleにも表示します。通知は、スーパー管理者、組織管理者、フェデレーション管理者、フェデレーション閲覧者といった役割を持つすべてのユーザーに送信されます。

. フェデレーションの詳細を確認し、[*フェデレーションを有効にする*] を選択します。
. プロセスを完了するには、[完了] を選択します。


フェデレーションを有効にすると、ユーザーは企業の資格情報を使用してNetApp Consoleにログインします。
