---
sidebar: sidebar 
permalink: task-console-assistant.html 
keywords: bluexp,netapp console,console assistant,assistant,setup assistant,get started,quick start,first time user,first time setup,setup wizard 
summary: 'NetAppコンソールを初めて使用する場合は、コンソール アシスタントが初期セットアップ プロセスを案内します。アシスタントを使用すると、 NetAppサポート サイト (NSS) アカウントの追加、コンソール エージェントの追加、クラスターの追加、ライセンスまたはサブスクリプションの追加が可能になり、データの管理を簡単に開始できるようになります。' 
---
= NetAppコンソールアシスタントの使用を開始する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
組織管理者ロールを持つNetAppコンソールを初めて使用する場合は、コンソール アシスタントを使用して初期セットアップ プロセスをガイドできます。アシスタントを使用すると、 NetAppサポート サイト (NSS) アカウントの追加、コンソール エージェントの追加、クラスターの追加、ライセンスまたはサブスクリプションの追加が可能になり、データの管理を簡単に開始できるようになります。



== コンソールアシスタントにアクセスするために必要な役割

コンソール アシスタントは、組織管理者の役割を持つユーザーのみが利用できます。



== コンソール アシスタントはいつ表示されますか?

必須のセットアップ タスクが完了するまで、コンソール アシスタントはNetAppコンソール ホーム ページで利用できます。

アシスタントを使用して、次のタスクを完了します。一部のタスクは必須です。

* NetAppサポート サイト (NSS) アカウントを追加します。
* コンソール エージェントを展開してストレージ エステートに接続します (必須の手順)。
* クラスターを追加または検出してシステムを管理します (必須の手順)。
* マーケットプレイスのサブスクリプションまたは PAYGO ライセンスを追加します。
* オープンデータサービスリンク。




== コンソールアシスタントを有効にする

デフォルトでは、 NetAppコンソールは、組織管理者ロールを持つ初めてのユーザーのホーム ページにコンソール アシスタントを表示します。


TIP: 自分または他の誰かが必須項目を完了した後にのみ、アシスタントを解任することができます。必須項目を完了すると、アシスタントは組織内のすべてのユーザーに対して終了し、再び表示されなくなります。



== コンソールアシスタントを使用して開始します

コンソール アシスタントは、次のタスクを実行してNetAppコンソール環境のセットアップをガイドします。

* NetAppサポート サイト (NSS) アカウントを追加します。
* オンプレミスまたはクラウドにコンソール エージェントを展開して、ストレージ資産に接続します。手動で展開するか、OVA をダウンロードして展開できます。この手順は必須です。
* クラスターを追加または検出してシステムを管理します。この手順は必須です。
* マーケットプレイスのサブスクリプションまたは PAYGO ライセンスを追加します。
* NetAppデータ サービスの詳細をご覧ください。

