---
sidebar: sidebar 
permalink: task-uninstall-agent.html 
keywords: uninstall, remove connector, uninstall connector, uninstall agent, remove agent 
summary: 問題をトラブルシューティングしたり、ホストから完全に削除したりするには、コンソール エージェントをアンインストールします。実行する必要がある手順は、使用している展開モードによって異なります。環境からコンソール エージェントを削除したら、コンソールからも削除できます。 
---
= コンソールエージェントをアンインストールして削除する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
問題をトラブルシューティングしたり、ホストから完全に削除したりするには、コンソール エージェントをアンインストールします。実行する必要がある手順は、使用している展開モードによって異なります。環境からコンソール エージェントを削除したら、コンソールからも削除できます。



== アウトバウンド接続がある場合はエージェントをアンインストールします

標準モードまたは制限モードを使用している場合 (つまり、エージェント ホストに送信接続がある場合)、以下の手順に従ってエージェントをアンインストールする必要があります。

.手順
. エージェントの Linux VM に接続します。
. Linux ホストから、アンインストール スクリプトを実行します。
+
`/opt/application/netapp/service-manager-2/uninstall.sh [silent]`

+
_silent_ は確認を求めることなくスクリプトを実行します。





== アウトバウンド接続がない場合にエージェントをアンインストールする

エージェントに送信接続がない場合（たとえば、プライベート モードの場合）、ホストからエージェント ソフトウェアを手動で削除する必要があります。

.手順
. コンソール エージェントの Linux VM に接続します。
. Linux ホストから、次のコマンドを実行します：
+
[source, cli]
----
/opt/application/netapp/ds/cleanup.sh
rm -rf /opt/application/netapp/
----
. Linux ホストから、古い未使用のコンテナ イメージ ファイルを削除して、再インストール用に /var ディレクトリの領域を解放します。
+
[role="tabbed-block"]
====
.ポッドマン
--
[source, cli]
----
podman system prune --all
----
--
.Docker
--
[source, cli]
----
docker system prune -a
----
--
====




== コンソールからコンソールエージェントを削除する

エージェント VM を削除した場合、またはエージェントをアンインストールした場合は、コンソールのエージェントのリストからそれを削除する必要があります。エージェント VM を削除するか、エージェント ソフトウェアをアンインストールすると、コンソールでエージェントのステータスが *切断* と表示されます。

コンソール エージェントを削除する場合は、次の点に注意してください。

* このアクションでは仮想マシンは削除されません。
* このアクションは元に戻すことはできません。コンソール エージェントを削除すると、再度追加することはできません。


.手順
. *管理 > エージェント*を選択します。
. *概要*ページで、切断されたエージェントのアクション メニューを選択し、*エージェントの削除*を選択します。
. 確認のためにエージェントの名前を入力し、「削除」を選択します。

