---
sidebar: sidebar 
permalink: task-install-connector-aws-marketplace.html 
keywords: install connector, aws connector installation, aws connector, install connector in aws, bluexp, aws marketplace, manual install, create connector 
summary: AWS Marketplace からコンソールエージェントを作成するには、ネットワークを設定し、AWS のアクセス許可を準備し、インスタンスの要件を確認してから、コンソールエージェントを作成する必要があります。 
---
= AWS Marketplaceからコンソールエージェントを作成する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
AWS Marketplace から直接 AWS にコンソールエージェントを作成します。  AWS Marketplace からコンソールエージェントを作成するには、ネットワークを設定し、AWS のアクセス許可を準備し、インスタンスの要件を確認してから、コンソールエージェントを作成する必要があります。

.開始する前に
* あなたはlink:concept-connectors.html["コンソールエージェントの理解"]。
* 確認すべきlink:reference-limitations.html["コンソールエージェントの制限"]。




== ステップ1: ネットワークを設定する

ハイブリッド クラウド リソースを管理するには、コンソール エージェントのネットワークの場所が次の要件を満たしていることを確認します。

VPCとサブネット:: コンソール エージェントを作成するときは、そのエージェントが存在する VPC とサブネットを指定する必要があります。


ターゲットネットワークへの接続:: コンソール エージェントには、システムを作成および管理する予定の場所へのネットワーク接続が必要です。たとえば、オンプレミス環境にCloud Volumes ONTAPシステムまたはストレージ システムを作成する予定のネットワークなどです。


アウトバウンドインターネットアクセス:: コンソール エージェントを展開するネットワークの場所には、特定のエンドポイントに接続するための送信インターネット接続が必要です。


コンソールエージェントから接続されたエンドポイント:: コンソール エージェントは、日常業務でパブリック クラウド環境内のリソースとプロセスを管理するために、次のエンドポイントに接続するために、送信インターネット アクセスを必要とします。
+
--
以下にリストされているエンドポイントはすべて CNAME エントリです。

[cols="2a,1a"]
|===
| エンドポイント | 目的 


 a| 
AWS サービス (amazonaws.com):

* クラウドフォーメーション
* エラスティックコンピューティングクラウド (EC2)
* アイデンティティとアクセス管理（IAM）
* キー管理サービス (KMS)
* セキュリティトークンサービス（STS）
* シンプルストレージサービス（S3）

 a| 
AWS リソースを管理します。エンドポイントは AWS リージョンによって異なります。 https://docs.aws.amazon.com/general/latest/gr/rande.html["詳細についてはAWSドキュメントを参照してください"^]



 a| 
\https://mysupport.netapp.com
 a| 
ライセンス情報を取得し、 AutoSupportメッセージをNetAppサポートに送信します。



 a| 
\https://signin.b2c.netapp.com
 a| 
NetAppサポート サイト (NSS) の資格情報を更新するか、 NetAppコンソールに新しい NSS 資格情報を追加します。



 a| 
\https://api.bluexp.netapp.com \https://netapp-cloud-account.auth0.com \https://netapp-cloud-account.us.auth0.com \https://console.netapp.com \https://components.console.bluexp.netapp.com \https://cdn.auth0.com
 a| 
NetAppコンソール内で機能とサービスを提供します。



 a| 
\https://bluexpinfraprod.eastus2.data.azurecr.io \https://bluexpinfraprod.azurecr.io
 a| 
コンソール エージェントのアップグレード用のイメージを取得します。

* 新しいエージェントを展開すると、検証チェックによって現在のエンドポイントへの接続がテストされます。使用する場合link:link:reference-networking-saas-console-previous.html["以前のエンドポイント"]、検証チェックは失敗します。この失敗を回避するには、検証チェックをスキップします。
+
以前のエンドポイントも引き続きサポートされますが、 NetApp、ファイアウォール ルールをできるだけ早く現在のエンドポイントに更新することをお勧めします。link:reference-networking-saas-console-previous.html#update-endpoint-list["エンドポイントリストを更新する方法を学ぶ"] 。

* ファイアウォールの現在のエンドポイントに更新すると、既存のエージェントは引き続き動作します。


|===
--


プロキシ サーバ:: NetApp は明示的プロキシ構成と透過的プロキシ構成の両方をサポートしています。透過プロキシを使用している場合は、プロキシ サーバーの証明書のみを提供する必要があります。明示的なプロキシを使用している場合は、IP アドレスと資格情報も必要になります。
+
--
* IPアドレス
* Credentials
* HTTPS証明書


--


ポート:: ユーザーが開始した場合、またはCloud Volumes ONTAPからNetAppサポートにAutoSupportメッセージを送信するためのプロキシとして使用された場合を除いて、コンソール エージェントへの着信トラフィックはありません。
+
--
* HTTP (80) と HTTPS (443) は、まれに使用するローカル UI へのアクセスを提供します。
* SSH（22）は、トラブルシューティングのためにホストに接続する必要がある場合にのみ必要です。
* アウトバウンド インターネット接続が利用できないサブネットにCloud Volumes ONTAPシステムを展開する場合は、ポート 3128 経由のインバウンド接続が必要です。
+
Cloud Volumes ONTAPシステムにAutoSupportメッセージを送信するためのアウトバウンド インターネット接続がない場合、コンソールは、コンソール エージェントに含まれているプロキシ サーバーを使用するようにそれらのシステムを自動的に構成します。唯一の要件は、コンソール エージェントのセキュリティ グループがポート 3128 経由の受信接続を許可していることを確認することです。コンソール エージェントを展開した後、このポートを開く必要があります。



--


NTP を有効にする:: NetApp Data Classification を使用して企業のデータ ソースをスキャンする予定の場合は、システム間で時刻が同期されるように、コンソール エージェントとNetApp Data Classification システムの両方で Network Time Protocol (NTP) サービスを有効にする必要があります。 https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["NetAppデータ分類の詳細"^]
+
--
コンソール エージェントを作成した後、このネットワーク アクセスを実装します。

--




== ステップ2: AWS権限を設定する

マーケットプレイスの展開を準備するには、AWS で IAM ポリシーを作成し、それを IAM ロールにアタッチします。  AWS Marketplace からコンソールエージェントを作成すると、その IAM ロールを選択するように求められます。

.手順
. AWS コンソールにログインし、IAM サービスに移動します。
. ポリシーを作成します。
+
.. *ポリシー > ポリシーの作成*を選択します。
.. *JSON*を選択し、その内容をコピーして貼り付けます。link:reference-permissions-aws.html["コンソールエージェントのIAMポリシー"] 。
.. 残りの手順を完了してポリシーを作成します。
+
使用する予定のNetAppデータ サービスに基づいて、2 番目のポリシーを作成する必要がある場合があります。標準リージョンの場合、権限は 2 つのポリシーに分散されます。 AWS の管理ポリシーの最大文字サイズ制限により、2 つのポリシーが必要になります。link:reference-permissions-aws.html["コンソールエージェントのIAMポリシーの詳細"] 。



. IAM ロールを作成します。
+
.. *[ロール] > [ロールの作成]*を選択します。
.. *AWS サービス > EC2* を選択します。
.. 作成したポリシーを添付して権限を追加します。
.. 残りの手順を完了してロールを作成します。




.結果
これで、AWS Marketplace からのデプロイ時に EC2 インスタンスに関連付けることができる IAM ロールが作成されました。



== ステップ3: インスタンス要件を確認する

コンソールエージェントを作成するときは、次の要件を満たす EC2 インスタンスタイプを選択する必要があります。

CPU:: 8コアまたは8vCPU
RAM:: 32 GB
AWS EC2インスタンスタイプ:: 上記の CPU および RAM の要件を満たすインスタンス タイプ。  t3.2xlarge をお勧めします。




== ステップ4: コンソールエージェントを作成する

AWS Marketplace から直接コンソールエージェントを作成します。

.タスク概要
AWS Marketplace からコンソールエージェントを作成すると、デフォルト設定を使用して AWS に EC2 インスタンスがデプロイされます。link:reference-connector-default-config.html["コンソールエージェントのデフォルト構成について学習します"] 。

.開始する前に
次のものが必要です:

* ネットワーク要件を満たす VPC とサブネット。
* コンソール エージェントに必要な権限を含むポリシーがアタッチされた IAM ロール。
* IAM ユーザーが AWS Marketplace にサブスクライブしたり、サブスクライブ解除したりするための権限。
* インスタンスの CPU および RAM 要件を理解すること。
* EC2 インスタンスのキーペア。


.手順
. に行く https://aws.amazon.com/marketplace/pp/prodview-jbay5iyfmu6ui["AWS Marketplace でのNetAppコンソールエージェントのリスト"^]
. マーケットプレイス ページで、[サブスクリプションを続行] を選択します。
. ソフトウェアをサブスクライブするには、「*利用規約に同意*」を選択します。
+
サブスクリプションのプロセスには数分かかる場合があります。

. サブスクリプションプロセスが完了したら、[構成に進む] を選択します。
. *このソフトウェアを構成する*ページで、正しいリージョンが選択されていることを確認し、*起動を続行*を選択します。
. *このソフトウェアの起動* ページの *アクションの選択* で、*EC2 経由で起動* を選択し、*起動* を選択します。
+
EC2 コンソールを使用してインスタンスを起動し、IAM ロールをアタッチします。これは、*Web サイトから起動* アクションでは不可能です。

. プロンプトに従ってインスタンスを構成してデプロイします。
+
** *名前とタグ*: インスタンスの名前とタグを入力します。
** *アプリケーションと OS イメージ*: このセクションはスキップします。コンソール エージェント AMI はすでに選択されています。
** *インスタンス タイプ*: リージョンの可用性に応じて、RAM と CPU の要件を満たすインスタンス タイプを選択します (t3.2xlarge が事前に選択されており、推奨されています)。
** *キーペア (ログイン)*: インスタンスに安全に接続するために使用するキーペアを選択します。
** *ネットワーク設定*: 必要に応じてネットワーク設定を編集します。
+
*** 必要な VPC とサブネットを選択します。
*** インスタンスにパブリック IP アドレスを割り当てるかどうかを指定します。
*** コンソール エージェント インスタンスに必要な接続方法 (SSH、HTTP、HTTPS) を有効にするセキュリティ グループ設定を指定します。
+
link:reference-ports-aws.html["AWS のセキュリティグループルールを表示する"] 。



** *ストレージの構成*: ルート ボリュームのデフォルトのサイズとディスク タイプを維持します。
+
ルートボリュームで Amazon EBS 暗号化を有効にする場合は、[*詳細*] を選択し、[*ボリューム 1*] を展開して、[*暗号化*] を選択し、KMS キーを選択します。

** *詳細*: *IAM インスタンス プロファイル* で、コンソール エージェントに必要な権限を含む IAM ロールを選択します。
** *概要*: 概要を確認し、*インスタンスの起動*を選択します。
+
AWS は指定された設定でコンソールエージェントを起動し、コンソールエージェントは約 10 分で実行されます。



+

NOTE: インストールが失敗した場合は、トラブルシューティングに役立つログとレポートを表示できます。link:task-troubleshoot-connector.html#troubleshoot-installation["インストールの問題をトラブルシューティングする方法を学びます。"]

. コンソール エージェント仮想マシンに接続しているホストとコンソール エージェントの URL から Web ブラウザーを開きます。
. ログイン後、コンソール エージェントを設定します。
+
.. コンソール エージェントに関連付けるコンソール組織を指定します。
.. システムの名前を入力します。
.. *安全な環境で実行していますか?* の下で、制限モードを無効のままにします。
+
コンソールを標準モードで使用するには、制限モードを無効にしておきます。安全な環境があり、このアカウントをコンソールのバックエンド サービスから切断する場合にのみ、制限モードを有効にする必要があります。もしそうなら、link:task-quick-start-restricted-mode.html["NetAppコンソールを制限モードで使い始めるための手順"] 。

.. *始めましょう*を選択します。




.結果
コンソール エージェントがインストールされ、コンソール組織に設定されました。

ウェブブラウザを開いて、 https://console.netapp.com["NetAppコンソール"^]コンソールでコンソール エージェントの使用を開始します。

コンソールエージェントを作成したのと同じ AWS アカウントに Amazon S3 バケットがある場合は、*システム* ページに Amazon S3 作業環境が自動的に表示されます。 https://docs.netapp.com/us-en/bluexp-s3-storage/index.html["NetAppコンソールから S3 バケットを管理する方法を学びます"^]
