---
sidebar: sidebar 
permalink: task-configuring-proxy.html 
keywords: proxy, proxy server, proxy, internet, HTTP, http, https, bluexp 
summary: 企業ポリシーでインターネットへのすべての通信にプロキシ サーバーの使用が求められている場合は、そのプロキシ サーバーを使用するようにエージェントを構成する必要があります。インストール時にコンソール エージェントがプロキシ サーバーを使用するように構成しなかった場合は、いつでもそのプロキシ サーバーを使用するようにコンソール エージェントを構成できます。 
---
= プロキシサーバーを使用するようにコンソールエージェントを構成する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
企業ポリシーでインターネットへのすべての通信にプロキシ サーバーの使用が求められている場合は、そのプロキシ サーバーを使用するようにエージェントを構成する必要があります。インストール時にコンソール エージェントがプロキシ サーバーを使用するように構成しなかった場合は、いつでもそのプロキシ サーバーを使用するようにコンソール エージェントを構成できます。

エージェントのプロキシ サーバーは、パブリック IP または NAT ゲートウェイなしでアウトバウンドのインターネット アクセスを可能にします。プロキシ サーバーは、Cloud Volumes ONTAPシステムではなく、コンソール エージェントに対してのみ送信接続を提供します。

Cloud Volumes ONTAPシステムにアウトバウンド インターネット アクセスがない場合、コンソールはコンソール エージェントのプロキシ サーバーを使用するようにシステムを構成します。コンソール エージェントのセキュリティ グループがポート 3128 経由の受信接続を許可していることを確認する必要があります。コンソール エージェントを展開した後、このポートを開きます。

コンソール エージェント自体に送信インターネット接続がない場合、 Cloud Volumes ONTAPシステムは構成されたプロキシ サーバーを使用できません。



== サポートされている構成

* Cloud Volumes ONTAPシステムにサービスを提供するエージェントでは、透過プロキシ サーバーがサポートされています。  Cloud Volumes ONTAPでNetAppデータ サービスを使用する場合は、透過プロキシ サーバーを使用できるCloud Volumes ONTAP専用のエージェントを作成します。
* 明示的なプロキシ サーバーは、Cloud Volumes ONTAPシステムを管理するエージェントやNetAppデータ サービスを管理するエージェントなど、すべてのエージェントでサポートされています。
* HTTP と HTTPS。
* プロキシ サーバーはクラウドまたはネットワーク内に配置できます。



IMPORTANT: プロキシを設定したら、プロキシの種類を変更することはできません。プロキシ タイプを変更する必要がある場合は、コンソール エージェントを削除し、新しいプロキシ タイプで新しいエージェントを追加します。



== コンソールエージェントで明示的なプロキシを有効にする

プロキシ サーバーを使用するようにコンソール エージェントを構成すると、そのエージェントとそれが管理するCloud Volumes ONTAPシステム (HA メディエーターを含む) はすべてプロキシ サーバーを使用します。

この操作により、コンソール エージェントが再起動されます。続行する前に、コンソール エージェントがアイドル状態であることを確認してください。

.手順
. *管理 > エージェント*を選択します。
. *概要*ページで、コンソール エージェントのアクション メニューを選択し、*エージェントの編集*を選択します。
+
編集するには、コンソール エージェントがアクティブである必要があります。

. *HTTP プロキシ構成*を選択します。
. 構成タイプ フィールドで *明示的なプロキシ* を選択します。
. *プロキシを有効にする*を選択します。
. 構文を使用してサーバーを指定します http://_address:port_[]または https://_address:port_[]
. サーバーに基本認証が必要な場合は、ユーザー名とパスワードを指定します。
+
次の点に注意してください。

+
** ユーザーはローカル ユーザーまたはドメイン ユーザーになります。
** ドメインユーザーの場合は、\ の ASCII コードを次のように入力する必要があります: domain-name%92user-name
+
例: netapp%92proxy

** コンソールは @ 文字を含むパスワードをサポートしていません。


. *保存*を選択します。




== コンソールエージェントの透過プロキシを有効にする

Cloud Volumes ONTAPのみが、コンソール エージェントでの透過プロキシの使用をサポートしています。  Cloud Volumes ONTAPに加えてNetAppデータ サービスを使用する場合は、データ サービス用またはCloud Volumes ONTAP用として別のエージェントを作成する必要があります。

透過プロキシを有効にする前に、次の要件が満たされていることを確認してください。

* エージェントは、透過プロキシ サーバーと同じネットワークにインストールされます。
* プロキシ サーバーで TLS 検査が有効になっています。
* 透過プロキシ サーバーで使用されている証明書と一致する PEM 形式の証明書があります。
* Cloud Volumes ONTAP以外のNetAppデータ サービスにはコンソール エージェントを使用しないでください。


既存のエージェントを透過プロキシ サーバーを使用するように構成するには、コンソール エージェント ホストのコマンド ラインから使用できるコンソール エージェント メンテナンス ツールを使用します。

プロキシ サーバーを構成すると、コンソール エージェントが再起動します。続行する前に、コンソール エージェントがアイドル状態であることを確認してください。

.手順
プロキシ サーバーの PEM 形式の証明書ファイルがあることを確認します。証明書がない場合は、ネットワーク管理者に問い合わせて取得してください。

. コンソール エージェント ホストでコマンド ライン インターフェイスを開きます。
. コンソール エージェント メンテナンス ツール ディレクトリに移動します。 `/opt/application/netapp/service-manager-2/agent-maint-console`
. 透過プロキシを有効にするには、次のコマンドを実行します。 `/home/ubuntu/<certificate-file>.pem`プロキシ サーバーのディレクトリと証明書ファイルの名前です。
+
[source, CLI]
----
./agent-maint-console proxy add -c /home/ubuntu/<certificate-file>.pem
----
+
証明書ファイルが PEM 形式であり、コマンドと同じディレクトリに存在することを確認するか、証明書ファイルへのフルパスを指定します。

+
[source, CLI]
----
./agent-maint-console proxy add -c /home/ubuntu/<certificate-file>.pem
----




=== コンソールエージェントの透過プロキシを変更する

コンソールエージェントの既存の透過プロキシサーバーを更新するには、 `proxy update`コマンドを使用して透過プロキシサーバーを削除するか、 `proxy remove`指示。詳細については、次のドキュメントを参照してください。link:reference-agent-maint-console.html["エージェントメンテナンスコンソール"] 。


IMPORTANT: プロキシを設定したら、プロキシの種類を変更することはできません。プロキシ タイプを変更する必要がある場合は、コンソール エージェントを削除し、新しいプロキシ タイプで新しいエージェントを追加します。



== インターネットへのアクセスが失われた場合は、コンソールエージェントプロキシを更新します。

ネットワークのプロキシ構成が変更されると、エージェントはインターネットにアクセスできなくなる可能性があります。たとえば、誰かがプロキシ サーバーのパスワードを変更したり、証明書を更新したりした場合などです。この場合、コンソール エージェント ホストから直接 UI にアクセスし、設定を更新する必要があります。コンソール エージェント ホストへのネットワーク アクセスがあり、コンソールにログインできることを確認します。



== 直接APIトラフィックを有効にする

コンソール エージェントがプロキシ サーバーを使用するように構成した場合は、コンソール エージェントで直接 API トラフィックを有効にして、プロキシを経由せずに API 呼び出しをクラウド プロバイダー サービスに直接送信できます。AWS、Azure、または Google Cloud で実行されているエージェントはこのオプションをサポートしています。

Cloud Volumes ONTAPで Azure Private Links を無効にしてサービス エンドポイントを使用する場合は、直接 API トラフィックを有効にします。そうしないと、トラフィックは適切にルーティングされません。

https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-enabling-private-link.html["Cloud Volumes ONTAPで Azure Private Link またはサービス エンドポイントを使用する方法の詳細"^]

.手順
. *管理 > エージェント*を選択します。
. *概要*ページで、コンソール エージェントのアクション メニューを選択し、*エージェントの編集*を選択します。
+
編集するには、コンソール エージェントがアクティブである必要があります。

. *直接 API トラフィックのサポート*を選択します。
. チェックボックスを選択してオプションを有効にし、[保存] を選択します。

