---
sidebar: sidebar 
permalink: task-update-agent-addressing.html 
keywords: agent ip address, agent uri, change ip address, edit uri, agent network, agent addressing 
summary: ネットワーク構成が変更された場合、クラウド プロバイダでエージェントの IP アドレスと NetApp Console に登録されている URI を更新する必要がある場合があります。 
---
= エージェントのアドレスとURIを更新する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ネットワーク構成が変更された場合、クラウド プロバイダでエージェントの IP アドレスと NetApp Console に登録されている URI を更新する必要がある場合があります。



== エージェントのIPアドレスを変更する

必要に応じて、クラウド プロバイダーによって割り当てられたエージェント インスタンスの内部 IP アドレスとパブリック IP アドレスを変更できます。

.手順
. クラウド プロバイダーの指示に従って、エージェント インスタンスのローカル IP アドレスまたはパブリック IP アドレス (あるいはその両方) を変更します。
. エージェント インスタンスを再起動して、新しいパブリック IP アドレスをコンソールに登録します。
. プライベート IP アドレスを変更した場合は、 Cloud Volumes ONTAP構成ファイルのバックアップ場所を更新して、バックアップがエージェントの新しいプライベート IP アドレスに送信されるようにします。
+
各Cloud Volumes ONTAPシステムのバックアップ場所を更新します。

+
.. Cloud Volumes ONTAP CLI から、権限レベルを高度に設定します。




[listing]
----
set -privilege advanced
----
. 現在のバックアップ ターゲットを表示するには、次のコマンドを実行します。


[listing]
----
system configuration backup settings show
----
. バックアップ ターゲットの IP アドレスを更新するには、次のコマンドを実行します。


[listing]
----
system configuration backup settings modify -destination <target-location>
----


== エージェントのURIを編集する

ネットワーク要件が変更された場合、コンソールエージェントのURIを更新します。これにより、ストレージインフラストラクチャの中断のない、安全かつコンプライアンスに準拠した管理が保証されます。

.手順
. *管理 > エージェント*を選択します。
. *概要*ページで、コンソール エージェントのアクション メニューを選択し、*エージェントの編集*を選択します。
+
編集するには、コンソール エージェントがアクティブである必要があります。

. エージェント URI を表示するには、*エージェント URI* バーを展開します。
. URI を追加および削除し、[適用] を選択します。

