---
sidebar: sidebar 
permalink: task-iam-manage-members-permissions.html 
keywords: user, service account, member, role, permissions, organization, project, folder, iam, identity and access management, federated groups, SSO, access roles, add members, grant permissions 
summary: 組織のメンバーを管理して、組織のリソース階層のさまざまなレベルにわたって権限を付与します。 
---
= NetApp Console組織にユーザーを追加する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Console内で、アクセスロールに基づいてユーザーにプロジェクトまたはフォルダへのアクセス権を付与します。_アクセスロール_には、メンバー（ユーザーまたはサービスアカウント）がリソース階層の割り当てられたレベルで特定のアクションを実行できるようにする一連の権限が含まれています。

.必要なアクセスロール
スーパー管理者、組織管理者、またはフォルダーまたはプロジェクトの管理者（管理しているフォルダーとプロジェクトの場合）。link:reference-iam-predefined-roles.html["アクセスロールについて学ぶ"]。



[[understand-how-access-is-granted-in-netapp-console]]
== NetApp Consoleでアクセスを許可する方法を理解する

NetApp Console はロールベースのアクセス制御（RBAC）を使用して権限を管理します。ユーザーには個別に、または連携グループを通じてロールを割り当てることができます。各ロールは、特定のリソースに対して許可される操作を定義します。

NetApp Consoleでアクセス権を付与する場合は、次の点に注意してください。

* すべてのユーザーは、たとえ連合グループの一員であっても、リソースへのアクセス権を付与される前に、まずNetApp Consoleにサインアップする必要があります。
* ロールが割り当てられたフェデレーション グループのメンバーであっても、ユーザーがリソースにアクセスするには、コンソールで各ユーザーにロールを明示的に割り当てる必要があります。
* コンソールから直接サービス アカウントを追加し、ロールを割り当てることができます。
* ユーザーまたはサービスアカウントにロールを割り当てる際は、サポートされているロールの中から選択できます。




[[add-members-to-your-organization]]
[[add-members]]
== 組織にメンバーを追加する

NetApp Consoleは、ユーザー アカウント、サービス アカウント、フェデレーション グループの 3 種類のメンバーをサポートしています。

ユーザーがフェデレーション グループに属している場合でも、ユーザーを追加してロールを割り当てるには、その前にNetApp Consoleにサインアップする必要があります。コンソールで直接サービス アカウントを作成します。

リソースにアクセスするには、すべてのメンバーに少なくとも 1 つのロールが明示的に割り当てられている必要があります。

メンバーを追加するときは、リソース レベル (組織、フォルダー、またはプロジェクト) を選択し、必要な権限を持つロールを割り当てます。



[[add-a-user]]
=== ユーザーを追加する

ユーザーはNetApp Consoleにサインアップしますが、リソースにアクセスできるように、組織管理者またはフォルダまたはプロジェクト管理者がユーザーを組織、フォルダ、またはプロジェクトに追加する必要があります。

.開始する前に：
ユーザーはNetApp Consoleにすでにサインアップしている必要があります。まだ登録していない場合は、 link:task-sign-up-saas.html["NetApp Consoleにサインアップします。"]


NOTE: フェデレーテッドグループの一部であるユーザーを追加する場合は、そのユーザーがすでにNetApp Consoleにサインアップしており、Consoleで明示的にロールが割り当てられていることを確認してください。NetAppでは、Organization viewerなどの最小限のアクセスロールを割り当てることを推奨しています。

.手順
. *管理 > IDとアクセス*を選択します。
. *メンバー*を選択します。
. *メンバーを追加*を選択します。
. *メンバータイプ*では*ユーザー*を選択したままにします。
. *ユーザーのメール*には、ユーザーが作成したログインに関連付けられているメール アドレスを入力します。
. *組織、フォルダ、またはプロジェクトを選択*セクションを使用して、メンバーに権限を与えるリソース階層のレベルを選択します。
+
次の点に注意してください。

+
** 権限を持つフォルダーとプロジェクトのみを選択できます。
** 組織またはフォルダを選択すると、そのすべてのコンテンツに対する権限がメンバーに付与されます。
** *組織管理者* ロールは組織レベルでのみ割り当てることができます。


. *カテゴリを選択*し、選択した組織、フォルダ、またはプロジェクトに関連付けられているリソースに対する権限をメンバーに付与する*ロール*を選択します。
+
ドロップダウンリストには、サポートされているロールのみが表示されます。link:reference-iam-predefined-roles.html["アクセスロールについて学ぶ"]。

. さらに多くのフォルダー、プロジェクト、またはロールへのアクセス権を付与するには、[*ロールの追加*] を選択し、フォルダー、プロジェクト、またはロールのカテゴリを選択して、ロールを選択します。
. *追加*を選択します。
+
コンソールはユーザーに指示を電子メールで送信します。





[[add-a-service-account]]
[[service-account]]
=== サービスアカウントを追加する

サービス アカウントを使用すると、タスクを自動化し、コンソール API に安全に接続できます。簡単なセットアップの場合はクライアント ID とシークレットを選択し、自動化環境またはクラウドネイティブ環境でのセキュリティを強化する場合は JWT (JSON Web Token) を選択します。セキュリティ要件を満たす方法を選択してください。

.開始する前に：
JWT 認証の場合は、公開鍵または証明書を準備します。

.手順
. *管理 > IDとアクセス*を選択します。
. *メンバー*を選択します。
. *メンバーを追加*を選択します。
. *メンバータイプ*では*サービスアカウント*を選択します。
. サービス アカウントの名前を入力します。
. JWT 認証を使用するには、[*秘密キー JWT 認証を使用する*] を選択し、公開 RSA キーまたは証明書をアップロードします。クライアント ID とシークレットを使用する場合はスキップします。
+
X.509証明書をPEM、CRT、またはCER形式でアップロードしてください。

+
.. 証明書の有効期限通知を設定します。 7日間または30日間を選択します。有効期限通知は、スーパー管理者または組織管理者のロールを持つユーザーにメールで送信され、コンソールに表示されます。


. *組織、フォルダ、またはプロジェクトを選択*セクションを使用して、メンバーに権限を与えるリソース階層のレベルを選択します。
+
次の点に注意してください。

+
** 権限を持つフォルダーとプロジェクトからのみ選択できます。
** 組織またはフォルダを選択すると、そのすべてのコンテンツに対する権限がメンバーに付与されます。
** *組織管理者* ロールは組織レベルでのみ割り当てることができます。


. *カテゴリー*を選択し、選択した組織、フォルダ、またはプロジェクト内のリソースに対するメンバー権限を付与する*ロール*を選択します。
+
link:reference-iam-predefined-roles.html["アクセスロールについて学ぶ"] 。

. さらに多くのフォルダー、プロジェクト、またはロールへのアクセス権を付与するには、[*ロールの追加*] を選択し、フォルダー、プロジェクト、またはロールのカテゴリを選択して、ロールを選択します。
. JWT認証を使用しなかった場合は、クライアントIDとクライアントシークレットをダウンロードまたはコピーしてください。
+
コンソールにはクライアント シークレットが 1 回だけ表示されます。安全にコピーしておけば、紛失した場合でも後で再作成できます。

. JWT 認証を選択した場合は、クライアント ID と JWT オーディエンスをダウンロードまたはコピーします。コンソールにはこの情報が一度だけ表示され、後で取得することはできません。
. *閉じる*を選択します。




[[add-a-federated-group-to-your-organization]]
== 組織にフェデレーショングループを追加する

アイデンティティ プロバイダー (IdP) から組織にフェデレーション グループを追加し、それに 1 つ以上のロールを割り当てることができます。フェデレーション グループのメンバーは、コンソールでグループに割り当てたロールを継承します。


IMPORTANT: コンソールにフェデレーション グループを追加してロールを割り当てると、IdP のグループのメンバーであり、すでにNetApp Console にサインアップして、Console で明示的にロールが割り当てられているユーザーのみがリソースにアクセスできます。NetApp では、これらのユーザーに組織閲覧者などの最小限のアクセス ロールを割り当てることを推奨します。

フェデレーション グループにロールを割り当てる前に、次の点を確認してください。

* IdP とコンソール間のフェデレーションを設定します。 link:concept-federation.html["フェデレーションを設定する方法を学習します。"]
* グループは既にIdPに存在し、NetApp Consoleへのアプリアクセス権が割り当てられている必要があります。


.手順
. *管理 > IDとアクセス*を選択します。
. *メンバー*を選択します。
. *メンバーを追加*を選択します。
. *メンバータイプ*では*フェデレーショングループ*を選択します。
. グループが所属するフェデレーションを選択します。
. *グループ名*には、IdP 内のグループの正確な名前を入力します。
. *組織、フォルダ、またはプロジェクトを選択*セクションを使用して、メンバーに権限を与えるリソース階層のレベルを選択します。
+
次の点に注意してください。

+
** 権限を持つフォルダーとプロジェクトからのみ選択できます。
** 組織またはフォルダを選択すると、そのすべてのコンテンツに対する権限がメンバーに付与されます。
** *組織管理者* ロールは組織レベルでのみ割り当てることができます。


. *カテゴリー*を選択し、選択した組織、フォルダ、またはプロジェクト内のリソースに対するメンバー権限を付与する*ロール*を選択します。
+
ドロップダウンリストには、サポートされているロールのみが表示されます。link:reference-iam-predefined-roles.html["アクセスロールについて学ぶ"]。

. さらに多くのフォルダー、プロジェクト、またはロールへのアクセス権を付与するには、[*ロールの追加*] を選択し、フォルダー、プロジェクト、またはロールのカテゴリを選択して、ロールを選択します。




[[related-information]]
== 関連情報

* link:concept-identity-and-access-management.html["NetApp Consoleのアイデンティティとアクセス管理について学ぶ"]
* link:task-iam-get-started.html["アイデンティティとアクセスを始める"]
* link:reference-iam-predefined-roles.html["NetApp Consoleアクセスロール"]
* https://docs.netapp.com/us-en/console-automation/tenancyv4/overview.html["IDとアクセスのためのAPIについて学ぶ"^]

