---
sidebar: sidebar 
permalink: task-agent-vm-config.html 
keywords: agent VM, vcenter, esxi, increase cpu, increase ram, vm maintenance, agent maintenance, agent operating system, agent host 
summary: コンソール エージェントを展開した後、既存の VCenter または ESXi ホストに変更を加えることができます。たとえば、コンソール エージェントをホストする VM インスタンスの CPU または RAM を増やすことができます。 
---
= コンソールエージェント用の VCenter または ESXi ホストを維持する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
コンソール エージェントを展開した後、既存の VCenter または ESXi ホストに変更を加えることができます。たとえば、コンソール エージェントをホストする VM インスタンスの CPU または RAM を増やすことができます。

VM Web コンソールを使用して次のメンテナンス タスクを実行します。

* ディスクサイズを増やす
* エージェントを再起動する
* 静的ルートを更新する
* 検索ドメインを更新する


.制限事項
コンソール経由でのエージェントのアップグレードはまだサポートされていません。さらに、IP アドレス、DNS、ゲートウェイに関する情報のみを表示できます。



== VMメンテナンスコンソールにアクセスする

VSphere クライアントからメンテナンス コンソールにアクセスできます。

.手順
. VSphere クライアントを開き、VCenter にログインします。
. コンソール エージェントをホストする VM インスタンスを選択します。
. *Web コンソールの起動* を選択します。
. VM インスタンスの作成時に指定したユーザー名とパスワードを使用して、VM インスタンスにログインします。ユーザー名は `maint`パスワードは、VM インスタンスの作成時に指定したパスワードです。




=== メインユーザーのパスワードを変更する

パスワードを変更することができます `maint`ユーザー。

.手順
. VSphere クライアントを開き、VCenter にログインします。
. コンソール エージェントをホストする VM インスタンスを選択します。
. *Web コンソールの起動* を選択します。
. VM インスタンスの作成時に指定したユーザー名とパスワードを使用して、VM インスタンスにログインします。ユーザー名は `maint`パスワードは、VM インスタンスの作成時に指定したパスワードです。
. 入力 `1`表示するには `System Configuration`メニュー。
. 入力 `1`メンテナンス ユーザーのパスワードを変更し、画面の指示に従います。




=== VMインスタンスのCPUまたはRAMを増やす

コンソール エージェントをホストする VM インスタンスの CPU または RAM を増やすことができます。

VCenter または ESXi ホストで VM インスタンス設定を編集し、メンテナンス コンソールを使用して変更を適用します。

.VSphereクライアントでの手順
. VSphere クライアントを開き、VCenter にログインします。
. コンソール エージェントをホストする VM インスタンスを選択します。
. VM インスタンスを右クリックし、[設定の編集] を選択します。
. /opt または /var パーティションに使用されるハード ドライブの領域を増やします。
+
.. /opt に使用されるハード ドライブの領域を増やすには、*ハード ディスク 2* を選択します。
.. /var に使用されるハードドライブの容量を増やすには、*ハード ディスク 3* を選択します。


. 変更を保存します。


.メンテナンスコンソールの手順
. VSphere クライアントを開き、VCenter にログインします。
. コンソール エージェントをホストする VM インスタンスを選択します。
. *Web コンソールの起動* を選択します。
. VM インスタンスの作成時に指定したユーザー名とパスワードを使用して、VM インスタンスにログインします。ユーザー名は `maint`パスワードは、VM インスタンスの作成時に指定したパスワードです。
. 入力 `1 to view the `System Configuration`メニュー。
. 入力 `2`画面上の指示に従います。コンソールは新しい設定をスキャンし、パーティションのサイズを増やします。




=== エージェントVMのネットワーク設定を表示する

VSphere クライアントでエージェント VM のネットワーク設定を表示して、ネットワークの問題を確認またはトラブルシューティングします。次のネットワーク設定は表示のみ可能で、更新はできません: IP アドレスと DNS の詳細。

.手順
. VSphere クライアントを開き、VCenter にログインします。
. コンソール エージェントをホストする VM インスタンスを選択します。
. *Web コンソールの起動* を選択します。
. VM インスタンスの作成時に指定したユーザー名とパスワードを使用して、VM インスタンスにログインします。ユーザー名は `maint`パスワードは、VM インスタンスの作成時に指定したパスワードです。
. 入力 `2`表示するには `Network Configuration`メニュー。
. 対応するネットワーク設定を表示するには、1 ～ 6 の数字を入力します。




=== エージェントVMの静的ルートを更新する

必要に応じて、エージェント VM の静的ルートを追加、更新、または削除します。

.手順
. VSphere クライアントを開き、VCenter にログインします。
. コンソール エージェントをホストする VM インスタンスを選択します。
. *Web コンソールの起動* を選択します。
. VM インスタンスの作成時に指定したユーザー名とパスワードを使用して、VM インスタンスにログインします。ユーザー名は `maint`パスワードは、VM インスタンスの作成時に指定したパスワードです。
. 入力 `2`表示するには `Network Configuration`メニュー。
. 入力 `7`静的ルートを更新し、画面の指示に従います。
. Enterキーを押します。
. 必要に応じて、追加の変更を加えます。
. 入力 `9`変更をコミットします。




=== エージェントVMのドメイン検索設定を更新する

エージェント VM の検索ドメイン設定を更新できます。

.手順
. VSphere クライアントを開き、VCenter にログインします。
. コンソール エージェントをホストする VM インスタンスを選択します。
. *Web コンソールの起動* を選択します。
. VM インスタンスの作成時に指定したユーザー名とパスワードを使用して、VM インスタンスにログインします。ユーザー名は `maint`パスワードは、VM インスタンスの作成時に指定したパスワードです。
. 入力 `2``表示するには `Network Configuration`メニュー。
. 入力 `8`ドメイン検索設定を更新し、画面の指示に従います。
. Enterキーを押します。
. 必要に応じて、追加の変更を加えます。
. 入力 `9`変更をコミットします。




=== エージェント診断ツールにアクセスする

コンソール エージェントの問題をトラブルシューティングするための診断ツールにアクセスします。  NetAppサポートは、問題のトラブルシューティング時にこれを実行するように依頼する場合があります。

.手順
. VSphere クライアントを開き、VCenter にログインします。
. コンソール エージェントをホストする VM インスタンスを選択します。
. *Web コンソールの起動* を選択します。
. VM インスタンスの作成時に指定したユーザー名とパスワードを使用して、VM インスタンスにログインします。ユーザー名は `maint`パスワードは、VM インスタンスの作成時に指定したパスワードです。
. 入力 `3`サポートと診断メニューを表示します。
. 入力 `1`診断ツールにアクセスし、画面上の指示に従います。 + たとえば、すべてのエージェント サービスが実行されていることを確認できます。link:task-troubleshoot-connector.html#check-agent-status["コンソールエージェントのステータスを確認する"^] 。




=== エージェント診断ツールにリモートでアクセスする

Putty などのツールを使用して、診断ツールにリモートでアクセスできます。ワンタイム パスワードを割り当てて、エージェント VM への SSH アクセスを有効にします。

SSH アクセスにより、コピー アンド ペーストなどの高度なターミナル機能が有効になります。

.手順
. VSphere クライアントを開き、VCenter にログインします。
. コンソール エージェントをホストする VM インスタンスを選択します。
. *Web コンソールの起動* を選択します。
. VM インスタンスの作成時に指定したユーザー名とパスワードを使用して、VM インスタンスにログインします。ユーザー名は `maint`パスワードは、VM インスタンスの作成時に指定したパスワードです。
. 入力 `3`表示するには `Support and Diagnostics`メニュー。
. 入力 `2`診断ツールにアクセスし、画面上の指示に従って 24 時間で期限が切れるワンタイム パスワードを設定します。
. PuttyなどのSSHツールを使用して、ユーザー名でエージェントVMに接続します。 `diag`および設定したワンタイムパスワード。

