---
sidebar: sidebar 
permalink: task-install-agent-aws-manual.html 
keywords: install connector, aws connector installation, aws connector, install connector in aws, bluexp, aws marketplace, manual install, create connector 
summary: AWS で実行されている Linux ホストにコンソールエージェントを手動でインストールできます。独自の Linux ホストにコンソールエージェントを手動でインストールするには、ホスト要件を確認し、ネットワークを設定し、AWS 権限を準備し、コンソールエージェントをインストールして、準備した権限を付与する必要があります。 
---
= AWSにConsoleエージェントを手動でデプロイする
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
AWS で実行されている Linux ホストに Console エージェントを手動でデプロイできます。独自の Linux ホストに Console エージェントを手動でデプロイするには、ホストの要件を確認し、ネットワークをセットアップし、AWS 権限を準備し、Console エージェントをデプロイしてから、準備した権限を指定する必要があります。

AWSにエージェントをデプロイすると、選択したVPC内でLinuxとNetApp Consoleエージェントソフトウェアを実行するEC2インスタンスが起動します。

.開始する前に
* link:concept-agent-install-options.html#agent-cloud-manual-deploy["AWS で手動でデプロイするタイミングを確認する"]。
* 確認すべきlink:reference-limitations.html["コンソールエージェントの制限"]。




== ステップ1: ホストの要件を確認する

コンソール エージェント ソフトウェアを実行しているホストが、オペレーティング システム、RAM、およびポートの要件を満たしていることを確認します。


NOTE: コンソール エージェントは、19000 ～ 19200 の UID と GID の範囲を予約します。この範囲は固定されており、変更することはできません。ホスト上のサードパーティ ソフトウェアがこの範囲内の UID または GID を使用している場合、エージェントのインストールは失敗します。  NetApp、競合を回避するためにサードパーティ ソフトウェアがインストールされていないホストの使用を推奨しています。

専用ホスト:: コンソール エージェントには専用のホストが必要です。次のサイズ要件を満たすアーキテクチャであれば、どれでもサポートされます。
+
--
* CPU: 8コアまたは8vCPU
* メモリ: 32 GB
* ディスク容量: ホストには 165 GB が推奨され、パーティション要件は次のとおりです。
+
** `/opt`: 120 GiBの空き容量が必要です
+
エージェントは `/opt`インストールするには `/opt/application/netapp`ディレクトリとその内容。

** `/var`: 40 GiBの空き容量が必要です
+
Console エージェントには `/var`このスペースが必要です。これは、Podman または Docker がこのディレクトリ内にコンテナを作成するように設計されているためです。具体的には、 `/var/lib/containers/storage`ディレクトリと Docker の場合は `/var/lib/docker`にコンテナを作成します。このスペースでは、外部マウントやシンボリックリンクは機能しません。





--
AWS EC2インスタンスタイプ:: CPU と RAM の要件を満たすインスタンス タイプ。  NetAppt3.2xlarge を推奨します。
ハイパーバイザー:: サポートされているオペレーティング システムを実行することが認定されているベア メタルまたはホスト型ハイパーバイザーが必要です。
[[podman-versions]]オペレーティングシステムとコンテナの要件:: コンソールを標準モードまたは制限モードで使用する場合、コンソール エージェントは次のオペレーティング システムでサポートされます。エージェントをインストールする前に、コンテナ オーケストレーション ツールが必要です。


[cols="2a,2a,2a,2a,2a"]
|===
| オペレーティング システム | サポートされるOSバージョン | サポートされているエージェントのバージョン | 必要なコンテナツール | SELinux 


 a| 
Red Hat Enterprise Linux



 a| 
 a| 
9.6

* 英語版のみ。
* ホストは Red Hat Subscription Management に登録されている必要があります。登録されていない場合、ホストはエージェントのインストール中に必要なサードパーティ製ソフトウェアを更新するためにリポジトリにアクセスできません。

 a| 
4.0.0 以降、コンソールが標準モードまたは制限モード
 a| 
Podman バージョン 5.4.0 と podman-compose 1.5.0。

<<podman-configuration,Podman の構成要件を表示する>> 。
 a| 
強制モードまたは許可モードでサポートされます



 a| 
 a| 
9.1～9.4

* 英語版のみ。
* ホストは Red Hat Subscription Management に登録されている必要があります。登録されていない場合、ホストはエージェントのインストール中に必要なサードパーティ製ソフトウェアを更新するためにリポジトリにアクセスできません。

 a| 
3.9.50 以降、コンソールが標準モードまたは制限モード
 a| 
Podman バージョン 4.9.4 と podman-compose 1.5.0。

<<podman-configuration,Podman の構成要件を表示する>> 。
 a| 
強制モードまたは許可モードでサポートされます



 a| 
 a| 
8.6～8.10

* 英語版のみ。
* ホストは Red Hat Subscription Management に登録されている必要があります。登録されていない場合、ホストはエージェントのインストール中に必要なサードパーティ製ソフトウェアを更新するためにリポジトリにアクセスできません。

 a| 
3.9.50 以降、コンソールが標準モードまたは制限モード
 a| 
Podman バージョン 4.6.1 または 4.9.4 と podman-compose 1.0.6。

<<podman-configuration,Podman の構成要件を表示する>> 。
 a| 
強制モードまたは許可モードでサポートされます



 a| 
Ubuntu



 a| 
 a| 
24.04 LTS
 a| 
3.9.45 以降、 NetApp Consoleが標準モードまたは制限モード
 a| 
Docker エンジン 23.0.6 から 28.0.0。
 a| 
サポート対象外



 a| 
 a| 
22.04 LTS
 a| 
3.9.50以降
 a| 
Docker エンジン 23.0.6 から 28.0.0。
 a| 
サポート対象外

|===
鍵ペア:: コンソールエージェントを作成するときは、インスタンスで使用する EC2 キーペアを選択する必要があります。
IMDSv2 使用時の PUT 応答ホップ制限:: IMDSv2 が有効になっている場合 (新しい EC2 インスタンスのデフォルト)、PUT 応答ホップ制限を 3 に設定します。そうしないと、エージェントのセットアップ中に UI 初期化エラーが表示されます。
+
--
* link:task-require-imdsv2.html["Amazon EC2 インスタンスで IMDSv2 の使用を必須にする"]
* https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-IMDS-existing-instances.html#modify-PUT-response-hop-limit["AWSドキュメント: PUTレスポンスのホップ制限を変更する"^]


--




== ステップ2: PodmanまたはDocker Engineをインストールする

オペレーティング システムに応じて、エージェントをインストールする前に Podman または Docker Engine のいずれかが必要になります。

* Red Hat Enterprise Linux 8 および 9 には Podman が必要です。
+
<<podman-versions,サポートされているPodmanのバージョンを表示する>> 。

* Ubuntu には Docker Engine が必要です。
+
<<podman-versions,サポートされている Docker エンジンのバージョンを表示する>> 。



.手順
[role="tabbed-block"]
====
.ポッドマン
--
Podman をインストールして設定するには、次の手順に従います。

* podman.socket サービスを有効にして起動します
* Python3をインストールする
* podman-composeパッケージをインストールします（Red Hatのバージョンによって異なります）
* podman-composeをPATH環境変数に追加する
* Red Hat Enterprise Linux を使用している場合は、Podman バージョンが CNI ではなく Netavark Aardvark DNS を使用していることを確認してください。



NOTE: DNS ポートの競合を避けるために、エージェントをインストールした後、aardvark-dns ポート (デフォルト: 53) を調整します。指示に従ってポートを構成します。

.手順
. ホストに podman-docker パッケージがインストールされている場合は削除します。
+
[source, cli]
----
dnf remove podman-docker
rm /var/run/docker.sock
----
. Podman をインストールします。
+
Podman は、公式の Red Hat Enterprise Linux リポジトリから入手できます。

+
.. Red Hat Enterprise Linux 9.6 の場合:
+
[source, cli]
----
sudo dnf install podman-5:<version>
----
+
<version> は、インストールする Podman のサポートされているバージョンです。<<podman-versions,サポートされているPodmanのバージョンを表示する>> 。

.. Red Hat Enterprise Linux 9.1 から 9.4 の場合:
+
[source, cli]
----
sudo dnf install podman-4:<version>
----
+
<version> は、インストールする Podman のサポートされているバージョンです。<<podman-versions,サポートされているPodmanのバージョンを表示する>> 。

.. Red Hat Enterprise Linux 8 の場合:
+
[source, cli]
----
sudo dnf install podman-4:<version>
----
+
<version> は、インストールする Podman のサポートされているバージョンです。<<podman-versions,サポートされているPodmanのバージョンを表示する>> 。



. podman.socket サービスを有効にして起動します。
+
[source, cli]
----
sudo systemctl enable --now podman.socket
----
. python3 をインストールします。
+
[source, cli]
----
sudo dnf install python3
----
. システムにまだインストールされていない場合は、EPEL リポジトリ パッケージをインストールします。
+
podman-compose は、Extra Packages for Enterprise Linux (EPEL) リポジトリから入手できるため、この手順は必須です。

. Red Hat Enterprise 9 を使用している場合:
+
.. EPEL リポジトリ パッケージをインストールします。


+
[source, cli]
----
sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
----
+
.. podman-compose パッケージ 1.5.0 をインストールします。
+
[source, cli]
----
sudo dnf install podman-compose-1.5.0
----


. Red Hat Enterprise Linux 8 を使用している場合:
+
.. EPEL リポジトリ パッケージをインストールします。
+
[source, cli]
----
sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
----
.. podman-compose パッケージ 1.0.6 をインストールします。
+
[source, cli]
----
sudo dnf install podman-compose-1.0.6
----
+

NOTE: 使用して `dnf install`コマンドは、PATH 環境変数に podman-compose を追加するための要件を満たしています。インストールコマンドは、すでにインストールされているpodman-composeを/usr/binに追加します。 `secure_path`ホスト上のオプション。

.. Red Hat Enterprise Linux 8 を使用している場合は、Podman バージョンが CNI ではなく Aardvark DNS を備えた NetAvark を使用していることを確認します。
+
... 次のコマンドを実行して、networkBackend が CNI に設定されているかどうかを確認します。
+
[source, cli]
----
podman info | grep networkBackend
----
... networkBackendが `CNI`、それを変更する必要があります `netavark`。
... インストール `netavark`そして `aardvark-dns`次のコマンドを使用します。
+
[source, cli]
----
dnf install aardvark-dns netavark
----
... 開く `/etc/containers/containers.conf`ファイルを編集し、network_backend オプションを変更して、「cni」の代わりに「netavark」を使用します。
+
もし `/etc/containers/containers.conf`存在しない場合は、設定を変更してください `/usr/share/containers/containers.conf`。

... podman を再起動します。
+
[source, cli]
----
systemctl restart podman
----
... 次のコマンドを使用して、networkBackend が「netavark」に変更されていることを確認します。
+
[source, cli]
----
podman info | grep networkBackend
----






--
.Dockerエンジン
--
Docker のドキュメントに従って Docker Engine をインストールします。

.手順
. https://docs.docker.com/engine/install/["Dockerからのインストール手順を見る"^]
+
サポートされている Docker エンジン バージョンをインストールするには、手順に従ってください。最新バージョンはコンソールでサポートされていないため、インストールしないでください。

. Docker が有効になっていて実行されていることを確認します。
+
[source, cli]
----
sudo systemctl enable docker && sudo systemctl start docker
----


--
====


== ステップ3: ネットワークを設定する

コンソール エージェントがハイブリッド クラウド内のリソースを管理できるように、ネットワークの場所が次の要件をサポートしていることを確認します。

ターゲットネットワークへの接続:: コンソール エージェントには、システムを作成および管理する予定の場所へのネットワーク接続が必要です。たとえば、オンプレミス環境にCloud Volumes ONTAPシステムまたはストレージ システムを作成する予定のネットワークなどです。


アウトバウンドインターネットアクセス:: コンソール エージェントを展開するネットワークの場所には、特定のエンドポイントに接続するための送信インターネット接続が必要です。


WebベースのNetApp Consoleを使用する際にコンピュータから接続されるエンドポイント::
+
--
WebブラウザからNetApp Consoleにアクセスするコンピュータは、複数のエンドポイントに接続できる機能を備えている必要があります。

link:reference-networking-saas-console.html["NetApp Console のネットワークを準備"]。

--


コンソールエージェントから接続されたエンドポイント:: コンソール エージェントは、日常業務でパブリック クラウド環境内のリソースとプロセスを管理するために、次のエンドポイントに接続するために、送信インターネット アクセスを必要とします。
+
--
以下にリストされているエンドポイントはすべて CNAME エントリです。

[cols="2a,1a"]
|===
| エンドポイント | 目的 


 a| 
AWS サービス (amazonaws.com):

* クラウドフォーメーション
* エラスティックコンピューティングクラウド (EC2)
* アイデンティティとアクセス管理（IAM）
* キー管理サービス (KMS)
* セキュリティトークンサービス（STS）
* シンプルストレージサービス（S3）

 a| 
AWS リソースを管理します。エンドポイントは AWS リージョンによって異なります。 https://docs.aws.amazon.com/general/latest/gr/rande.html["詳細についてはAWSドキュメントを参照してください"^]



 a| 
Amazon FSx for NetApp ONTAP：

* api.workloads.netapp.com

 a| 
Webベースのコンソールは、このエンドポイントに接続して Workload Factory API と対話し、FSx for ONTAPベースのワークロードを管理および操作します。



 a| 
\https://mysupport.netapp.com
 a| 
ライセンス情報を取得し、AutoSupportメッセージをNetAppサポートに送信します。



 a| 
\https://signin.b2c.netapp.com
 a| 
NetAppサポート サイト (NSS) の資格情報を更新したり、 NetApp Consoleに新しい NSS 資格情報を追加したりします。



 a| 
\https://support.netapp.com
 a| 
ライセンス情報を取得し、AutoSupportメッセージをNetAppサポートに送信するとともに、Cloud Volumes ONTAPのソフトウェアアップデートを受信するため。



 a| 
\https://api.bluexp.netapp.com \https://netapp-cloud-account.auth0.com \https://netapp-cloud-account.us.auth0.com \https://console.netapp.com \https://components.console.netapp.com \https://cdn.auth0.com
 a| 
NetApp Console内で機能とサービスを提供します。



 a| 
\https://bluexpinfraprod.eastus2.data.azurecr.io \https://bluexpinfraprod.azurecr.io
 a| 
コンソール エージェントのアップグレード用のイメージを取得します。

* 新しいエージェントを展開すると、検証チェックによって現在のエンドポイントへの接続がテストされます。使用する場合link:reference-networking-saas-console-previous.html["以前のエンドポイント"]、検証チェックは失敗します。この失敗を回避するには、検証チェックをスキップします。
+
以前のエンドポイントも引き続きサポートされますが、 NetApp、ファイアウォール ルールをできるだけ早く現在のエンドポイントに更新することをお勧めします。link:reference-networking-saas-console-previous.html#update-endpoint-list["エンドポイントリストを更新する方法を学ぶ"] 。

* ファイアウォールの現在のエンドポイントに更新すると、既存のエージェントは引き続き動作します。


|===
--


プロキシ サーバ:: NetApp は明示的プロキシ構成と透過的プロキシ構成の両方をサポートしています。透過プロキシを使用している場合は、プロキシ サーバーの証明書のみを提供する必要があります。明示的なプロキシを使用している場合は、IP アドレスと資格情報も必要になります。
+
--
* IPアドレス
* Credentials
* HTTPS証明書


--


ポート:: コンソールエージェントへの受信トラフィックはありません。ただし、ユーザーが開始した場合、またはプロキシとして使用してAutoSupportメッセージをCloud Volumes ONTAPからNetAppサポートに送信する場合は除きます。
+
--
* HTTP (80) と HTTPS (443) は、まれにしか使用されないローカル UI へのアクセスを提供します。
* SSH（22）は、トラブルシューティングのためにホストに接続する必要がある場合にのみ必要です。
* アウトバウンド インターネット接続が利用できないサブネットにCloud Volumes ONTAPシステムを展開する場合は、ポート 3128 経由のインバウンド接続が必要です。
+
Cloud Volumes ONTAPシステムにAutoSupportメッセージを送信するためのアウトバウンド インターネット接続がない場合、コンソールは、コンソール エージェントに含まれているプロキシ サーバーを使用するようにそれらのシステムを自動的に構成します。唯一の要件は、コンソール エージェントのセキュリティ グループがポート 3128 経由の受信接続を許可していることを確認することです。コンソール エージェントを展開した後、このポートを開く必要があります。



--


NTP を有効にする:: NetApp Data Classificationを使用して企業データソースをスキャンする予定がある場合は、コンソールエージェントとNetApp Data Classificationシステムの両方でネットワークタイムプロトコル（NTP）サービスを有効にして、システム間で時刻が同期されるようにする必要があります https://docs.netapp.com/us-en/data-services-data-classification/concept-cloud-compliance.html["NetApp Data Classificationの詳細については、こちらをご覧ください"^]。




== ステップ4: コンソールのAWS権限を設定する

次のいずれかのオプションを使用して、 NetApp Consoleに AWS 権限を付与します。

* オプション 1: IAM ポリシーを作成し、EC2 インスタンスに関連付けることができる IAM ロールにポリシーをアタッチします。
* オプション 2: 必要な権限を持つ IAM ユーザーの AWS アクセスキーをコンソールに提供します。


コンソールの権限を準備するには、手順に従ってください。

[role="tabbed-block"]
====
.IAMのロール
--
.手順
. AWS コンソールにログインし、IAM サービスに移動します。
. ポリシーを作成します。
+
.. *ポリシー > ポリシーの作成*を選択します。
.. *JSON*を選択し、その内容をコピーして貼り付けます。link:reference-permissions-aws.html["コンソールエージェントのIAMポリシー"] 。
.. 残りの手順を完了してポリシーを作成します。
+
使用予定のNetAppデータサービスによっては、2つ目のポリシーを作成する必要があるかもしれません。標準リージョンでは、権限は2つのポリシーに分散されています。AWSのマネージドポリシーには文字数制限があるため、2つのポリシーが必要です。link:reference-permissions-aws.html["コンソールエージェントのIAMポリシーの詳細"]。



. IAM ロールを作成します。
+
.. *[ロール] > [ロールの作成]*を選択します。
.. *AWS サービス > EC2* を選択します。
.. 作成したポリシーを添付して権限を追加します。
.. 残りの手順を完了してロールを作成します。




.結果
コンソールエージェントをインストールした後、EC2 インスタンスに関連付けることができる IAM ロールが作成されます。

--
.AWS アクセスキー
--
.手順
. AWS コンソールにログインし、IAM サービスに移動します。
. ポリシーを作成します。
+
.. *ポリシー > ポリシーの作成*を選択します。
.. *JSON*を選択し、その内容をコピーして貼り付けます。link:reference-permissions-aws.html["コンソールエージェントのIAMポリシー"] 。
.. 残りの手順を完了してポリシーを作成します。
+
使用する予定のNetAppデータ サービスによっては、2 番目のポリシーを作成する必要がある場合があります。

+
標準リージョンの場合、権限は 2 つのポリシーに分散されます。 AWS の管理ポリシーの最大文字サイズ制限により、2 つのポリシーが必要になります。link:reference-permissions-aws.html["コンソールエージェントのIAMポリシーの詳細"] 。



. IAM ユーザーにポリシーをアタッチします。
+
** https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create.html["AWSドキュメント: IAMロールの作成"^]
** https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_manage-attach-detach.html["AWSドキュメント: IAMポリシーの追加と削除"^]


. コンソール エージェントをインストールした後、 NetApp Consoleに追加できるアクセス キーがユーザーにあることを確認します。


.結果
これで、必要な権限を持つ IAM ユーザーと、コンソールに提供できるアクセス キーが作成されました。

--
====


== ステップ5: コンソールエージェントをインストールする

前提条件を満たしたら、Linux ホストにソフトウェアを手動でインストールします。

.開始する前に
次のものが必要です:

* コンソール エージェントをインストールするためのルート権限。
* コンソール エージェントからのインターネット アクセスにプロキシが必要な場合のプロキシ サーバーの詳細。
+
インストール後にプロキシ サーバを設定するオプションがありますが、設定するにはコンソールエージェントを再起動する必要があります。

* プロキシ サーバーが HTTPS を使用する場合、またはプロキシがインターセプト プロキシである場合は、CA 署名証明書。



NOTE: コンソール エージェントを手動でインストールする場合、透過プロキシ サーバーの証明書を設定することはできません。透過プロキシ サーバーの証明書を設定する必要がある場合は、インストール後にメンテナンス コンソールを使用する必要があります。詳細はこちら link:reference-agent-maint-console-proxy.html["エージェントメンテナンスコンソール"]。

.タスク概要
インストール後、新しいバージョンが利用可能な場合、コンソール エージェントは自動的に更新されます。

.手順
. ホストに _http_proxy_ または _https_proxy_ システム変数が設定されている場合は、それらを削除します。
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
これらのシステム変数を削除しないと、インストールは失敗します。

. コンソール エージェント ソフトウェアをダウンロードし、Linux ホストにコピーします。  NetApp ConsoleまたはNetAppサポート サイトからダウンロードできます。
+
** NetApp Console：*エージェント > 管理 > エージェントのデプロイ > オンプレミス > 手動インストール* に移動します。
+
エージェントインストーラファイルをダウンロードするか、ファイルへのURLをコピーするかを選択します。



+

NOTE: ネットワークまたはクラウドで使用するための「オンライン」エージェント インストーラーをダウンロードします。NetApp Console エージェントには別の「オフライン」インストーラーが用意されていますが、プライベート モードの展開でのみサポートされます。

+
** NetApp Support Site（まだコンソールへのアクセス権がない場合に必要） https://mysupport.netapp.com/site/products/all/details/netapp-console/downloads-tab["NetAppサポート サイト"^]。


. スクリプトを実行するための権限を割り当てます。
+
[source, cli]
----
chmod +x NetApp_Console_Agent_Cloud_<version>
----
+
<version> は、ダウンロードしたコンソール エージェントのバージョンです。

. Government Cloud 環境にインストールする場合は、構成チェックを無効にします。link:task-troubleshoot-agent.html#disable-config-check["手動インストールの構成チェックを無効にする方法を説明します。"]
. インストール スクリプトを実行します。
+
[source, cli]
----
./NetApp_Console_Agent_Cloud_<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>
----
+
ネットワークでインターネットアクセスにプロキシが必要な場合は、プロキシ情報を追加する必要があります。インストール中に明示的にプロキシを追加できます。 `--proxy`および `--cacert`パラメータはオプションであり、追加を要求されることはありません。明示的なプロキシ サーバがある場合は、示されているようにパラメータを入力する必要があります。




NOTE: 透過プロキシを設定する場合は、エージェントのインストール後に設定できます。link:reference-agent-maint-console-proxy.html["エージェントメンテナンスコンソールについて学ぶ"]。

+

CA署名付き証明書を使用した明示的なプロキシ サーバの設定例を以下に示します：

+

[source, cli]
----
./NetApp_Console_Agent_Cloud_v4.0.0 --proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
----
+
`--proxy` 次のいずれかの形式を使用して、Console エージェントが HTTP または HTTPS プロキシ サーバを使用するように設定します：

+ * \http://address:port * \http://user-name:password@address:port * \http://domain-name%92user-name:password@address:port * \https://address:port * \https://user-name:password@address:port * \https://domain-name%92user-name:password@address:port

+ 以下の点に注意してください：

+ ** ユーザーは、ローカル ユーザーまたはドメイン ユーザーにすることができます。** ドメイン ユーザーの場合は、上記のように \ の ASCII コードを使用する必要があります。** Console エージェントは、@ 文字を含むユーザー名またはパスワードをサポートしていません。** パスワードに次の特殊文字が含まれている場合は、その特殊文字の前にバックスラッシュを付けてエスケープする必要があります：& または !

+ 例：

+ \http://bxpproxyuser:netapp1\!@address:3128

. Podman を使用した場合は、aardvark-dns ポートを調整する必要があります。
+
.. コンソール エージェント仮想マシンに SSH で接続します。
.. podman _/usr/share/containers/containers.conf_ ファイルを開き、Aardvark DNS サービス用に選択したポートを変更します。たとえば、54 に変更します。
+
[source, cli]
----
vi /usr/share/containers/containers.conf
----
+
例えば：

+
[source, text]
----
# Port to use for dns forwarding daemon with netavark in rootful bridge
# mode and dns enabled.
# Using an alternate port might be useful if other DNS services should
# run on the machine.
#
dns_bind_port = 54
----
.. コンソール エージェント仮想マシンを再起動します。


. インストールが完了するまでお待ちください。
+
プロキシ サーバーを指定した場合、インストールの最後に、コンソール エージェント サービス (occm) が 2 回再起動します。




NOTE: インストールが失敗した場合は、インストール レポートとログを表示して問題の解決に役立てることができます。link:task-troubleshoot-agent.html#troubleshoot-installation["インストールの問題をトラブルシューティングする方法を学びます。"]

. コンソール エージェント仮想マシンに接続しているホストから Web ブラウザを開き、次の URL を入力します。
+
https://_ipaddress_[]

. ログイン後、コンソール エージェントを設定します。
+
.. コンソール エージェントに関連付ける組織を指定します。
.. システムの名前を入力します。
.. *安全な環境で実行していますか?* の下で、制限モードを無効のままにします。
+
以下の手順ではコンソールを標準モードで使用する方法について説明しているため、制限モードは無効にしておく必要があります。安全な環境があり、このアカウントをバックエンド サービスから切断する場合にのみ、制限モードを有効にする必要があります。もしそうなら、link:task-quick-start-restricted-mode.html["NetApp Consoleを制限モードで使い始めるための手順に従います"] 。

.. *始めましょう*を選択します。




Console エージェントを作成したのと同じ AWS アカウントに Amazon S3 バケットがある場合、Amazon S3 ストレージ システムが *Systems* ページに自動的に表示されます。 https://docs.netapp.com/us-en/storage-management-s3-storage/index.html["NetApp Consoleから S3 バケットを管理する方法を学びます"^]



== ステップ6: NetApp Consoleに権限を付与する

コンソールエージェントをインストールした後、コンソールエージェントが AWS 内のデータとストレージインフラストラクチャを管理できるように、設定した AWS 権限を提供します。

[role="tabbed-block"]
====
.IAMのロール
--
作成した IAM ロールをコンソールエージェント EC2 インスタンスにアタッチします。

.手順
. Amazon EC2 コンソールに移動します。
. *インスタンス*を選択します。
. コンソール エージェント インスタンスを選択します。
. *アクション > セキュリティ > IAM ロールの変更*を選択します。
. IAM ロールを選択し、*IAM ロールの更新*を選択します。


に行く https://console.netapp.com["NetApp Console"^]コンソール エージェントの使用を開始します。

--
.AWS アクセスキー
--
必要な権限を持つ IAM ユーザーの AWS アクセスキーをコンソールに提供します。

.手順
. コンソールで正しいコンソール エージェントが現在選択されていることを確認します。
. *管理 > 資格情報*を選択します。
. *組織の資格情報*を選択します。
. *資格情報の追加*を選択し、ウィザードの手順に従います。
+
.. *資格情報の場所*: *Amazon Web Services > エージェント*を選択します。
.. *資格情報の定義*: AWS アクセスキーとシークレットキーを入力します。
.. *マーケットプレイス サブスクリプション*: 今すぐサブスクライブするか、既存のサブスクリプションを選択して、マーケットプレイス サブスクリプションをこれらの資格情報に関連付けます。
.. *確認*: 新しい資格情報の詳細を確認し、[*追加*] を選択します。




に行く https://console.netapp.com["NetApp Console"^]コンソール エージェントの使用を開始します。

--
====