---
sidebar: sidebar 
permalink: task-sign-up-saas.html 
keywords: sign up, signing up, sign in, signing in, login with netapp, log in with netapp, create account, account, log in with nss, nss, nss login 
summary: コンソールを使い始めるには、まずNetApp Support Siteの認証情報を使用してサインアップまたはログインするか、 NetApp Consoleログインを作成します。会社で最初にサインアップするユーザーの場合は、組織管理者としてコンソールで新しい組織を作成します。会社にすでに組織がある場合は、サインアップまたはログインしてアクセスできます。 
---
= NetApp Consoleにサインアップまたはログイン
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
コンソールを使用するには、 NetApp Support Siteの認証情報を使用してサインアップまたはログインするか、 NetApp Consoleのログインを作成します。社内で最初にサインアップする場合は、管理者として新しい組織を作成します。会社にすでに組織がある場合は、既存のNetApp Support Siteの認証情報または会社のシングル サインオン (SSO) を使用してサインアップまたはログインします。



[[sign-up-for-netapp-console-as-the-initial-organization-administrator]]
== NetApp Consoleに初期組織管理者としてサインアップする

会社にNetApp Console組織がない場合は、サインアップして作成してください。最初のユーザーは組織管理者となり、ユーザー アカウントと権限を管理します。後からロールを更新したり、管理者を追加したりすることもできます。

.手順
. Webブラウザを開いて、 https://console.netapp.com["NetApp Console"^]にアクセスします。
. NetApp Support Siteのアカウントをお持ちの場合は、*ログイン* ページでアカウントに関連付けられている電子メール アドレスを直接入力します。
+
コンソールは、この最初のログインの一部として、NetApp Support Siteの資格情報を使用してサインアップします。

. コンソール ログインを作成してサインアップする場合は、[サインアップ] を選択します。
+
.. *サインアップ*ページで必要な情報を入力し、*次へ*を選択します。
+

NOTE: サインアップフォームでは英語の文字のみ使用できます。

.. 受信トレイで、電子メール アドレスを確認するための手順が記載されたNetAppからの電子メールを確認してください。
+
サインアップを完了するには、メールアドレスを確認してください。



. ログイン後、エンドユーザー使用許諾契約書を確認して同意します。
. *ようこそ*ページで組織を作成します。
. *始めましょう*を選択します。


+ 初めてのユーザーおよび組織管理者は、ガイド付きのプロセスに従ってストレージ リソースの追加、コンソール エージェントの作成などを行います。 link:task-console-assistant.html["コンソール アシスタントの使用について説明します。"^]

.次のステップ
管理者は、コンソール アシスタントに含まれる手順を完了した後、ID とアクセス戦略を計画し、組織にユーザーを追加し、ロールを割り当てる必要があります。 link:task-iam-get-started.html["NetApp ConsoleのIDとアクセス管理について学ぶ"^]



[[sign-up-or-login-to-netapp-console-when-an-organization-already-exists]]
== 組織がすでに存在する場合は、 NetApp Consoleにサインアップまたはログインしてください

会社にすでにNetApp Console組織がある場合は、サインアップまたはログインしてアクセスしてください。サインアップまたはログインの方法は、会社が ID フェデレーションを使用しているか、 NetApp Support Siteの認証情報を持っているかによって異なります。そうでない場合は、 NetApp Consoleログインを作成します。

.手順
. Webブラウザを開いて、 https://console.netapp.com["NetApp Console"^]にアクセスします。
. NetApp Support Siteのアカウントをお持ちの場合、または会社でシングル サインオン(SSO) を設定している場合は、[*ログイン*] ページに関連付けられている電子メール アドレスまたは SSO 資格情報を入力します。指示に従ってログインを完了してください。
+
どちらの場合も、最初のログインの一環としてコンソールにサインアップされます。

. コンソール ログインを作成してサインアップする場合は、[サインアップ] を選択します。
+
.. *サインアップ*ページで必要な情報を入力し、*次へ*を選択します。
+

NOTE: サインアップフォームでは英語の文字のみ使用できます。

.. 受信トレイで、電子メール アドレスを確認するための手順が記載されたNetAppからの電子メールを確認してください。
+
サインアップを完了するには、メールアドレスを確認してください。



. ログイン後、エンドユーザー使用許諾契約書を確認して同意します。
. システムから組織の作成を求められた場合は、ダイアログ ボックスを閉じてコンソール管理者に伝え、コンソール組織に追加してアクセス権を付与してもらいます。 link:task-user-settings.html#contact-admin["組織管理者に連絡する方法について説明します。"^]


.次のステップ
組織へのアクセス権が付与されると、ストレージの管理と割り当てられたデータ サービスの使用を開始できます。
