---
sidebar: sidebar 
permalink: task-sign-up-saas.html 
keywords: sign up, signing up, sign in, signing in, login with netapp, log in with netapp, create account, account, log in with nss, nss, nss login 
summary: NetApp Consoleは、Web ベースのコンソールからアクセスできます。コンソールを使い始めるには、まず、 NetAppサポート サイトの認証情報を使用してサインアップまたはログインするか、 NetApp Consoleログインを作成します。 
---
= NetApp Consoleにサインアップまたはログイン
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Consoleは、Web ベースのコンソールからアクセスできます。コンソールを使い始めるには、まず、 NetAppサポート サイトの認証情報を使用してサインアップまたはログインするか、 NetApp Consoleログインを作成します。

.タスク概要
コンソールに初めてアクセスする場合は、次のいずれかのオプションを使用してサインアップまたはログインできます。

NetApp Consoleログイン:: ログインを作成してサインアップできます。この認証方法では、電子メール アドレスとパスワードを指定する必要があります。メールアドレスを確認したら、ログインして、まだ所属していない場合は組織を作成できます。
NetAppサポート サイト (NSS) の認証情報:: 既存のNetAppサポート サイトの認証情報をお持ちの場合は、コンソールにサインアップする必要はありません。  NSS 認証情報を使用してログインすると、まだ組織に属していない場合は、コンソールで組織を作成するように求められます。
+
--
登録したメールアドレスにワンタイムパスコード（OTP）が送信されます。サインインを試行するたびに新しい OTP が生成されます。

--
フェデレーション接続:: 会社にすでにNetApp Consoleインスタンスがある場合は、コンソール管理者が、企業ディレクトリの資格情報 (フェデレーション ID) を使用してログインするためのシングル サインオンを設定している可能性があります。
+
--
link:concept-federation.html["NetApp Consoleでアイデンティティフェデレーションを使用する方法を学びます"] 。

--


.手順
. ウェブブラウザを開いて、 https://console.netapp.com["NetApp Console"^]
. NetAppサポート サイトのアカウントをお持ちの場合、またはすでに ID フェデレーションを設定している場合は、*ログイン* ページでアカウントに関連付けられている電子メール アドレスを直接入力します。
+
どちらの場合も、最初のログインの一環としてコンソールにサインアップされます。

. コンソール ログインを作成してサインアップする場合は、[サインアップ] を選択します。
+
.. *サインアップ*ページで必要な情報を入力し、*次へ*を選択します。
+
サインアップフォームでは英語の文字のみが許可されていることに注意してください。

.. 受信トレイで、電子メール アドレスを確認するための手順が記載されたNetAppからの電子メールを確認してください。
+
コンソールにログインする前にこの手順を実行する必要があります。



. ログイン後、エンドユーザー使用許諾契約書を確認し、条件に同意します。
+
ユーザー アカウントがまだコンソール組織に属していない場合は、組織を作成するように求められます。

. *ようこそ*ページで、コンソール組織の名前を入力します。
+
コンソールは、コンソールの ID およびアクセス管理 (IAM) の最上位要素である組織を定義します。link:concept-identity-and-access-management.html["IAMの詳細"] 。

+
会社にすでに組織があり、その組織に参加したい場合は、コンソールを閉じて、組織管理者に組織への関連付けを依頼してください。追加されたら、ログインしてコンソール組織にアクセスできるようになります。link:task-iam-manage-members-permissions#add-members["既存の組織にメンバーを追加する方法を学ぶ"] 。

. *始めましょう*を選択します。

