---
sidebar: sidebar 
permalink: task-console-assistant.html 
keywords: bluexp,netapp console,console assistant,assistant,setup assistant,get started,quick start,first time user,first time setup,setup wizard 
summary: 'NetApp Consoleを初めて使用する場合は、コンソール アシスタントが初期セットアップ プロセスを案内します。アシスタントを使用すると、 NetAppサポート サイト (NSS) アカウントの追加、コンソール エージェントの追加、クラスターの追加、ライセンスまたはサブスクリプションの追加が可能になり、データの管理を簡単に開始できるようになります。' 
---
= NetApp Consoleアシスタントの使用を開始する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
組織管理者ロールを持つNetApp Console(SaaS) を初めて使用する場合は、コンソール アシスタントを使用して初期セットアップ プロセスをガイドできます。アシスタントを使用すると、 NetApp Support Site(NSS) アカウントの追加、コンソール エージェントの追加、クラスターの追加、ライセンスまたはサブスクリプションの追加が可能になり、データの管理を簡単に開始できるようになります。



[[required-roles-to-access-the-console-assistant]]
== コンソールアシスタントにアクセスするために必要な役割

コンソール アシスタントは、組織管理者の役割を持つユーザーのみが利用できます。

デフォルトでは、 NetApp Consoleは、組織管理者ロールを持つ初めてのユーザーのホーム ページにコンソール アシスタントを表示します。コンソール エージェントの作成とシステムの追加という必須タスクが完了するまで、引き続き使用できます。

アシスタントを使用してこれらのタスクを完了すると、NetApp Console環境の最小限のセットアップができます：

* NetAppサポート サイト (NSS) アカウントを追加します。
+
link:task-adding-nss-accounts.html["NSSアカウントを追加する方法を学ぶ"]。

* コンソール エージェントを展開してストレージ エステートに接続します。
+
link:task-install-agent-on-prem.html["オンプレミスでコンソール エージェントをインストールする方法を学習します。"]

* クラスターを追加または検出してストレージ システムを管理する
* マーケットプレイスのサブスクリプションまたは PAYGO ライセンスを追加します。
+
link:https://docs.netapp.com/us-en/console-licenses-subscriptions/index.html["ライセンスとサブスクリプションを追加する方法を学ぶ"^]。

* データ サービス情報を確認します。

