---
sidebar: sidebar 
permalink: task-manage-user-credentials.html 
keywords: credentials, ontap credentials, update ontap credentials, update ontap password, nss account, nss credentials, nss login, nss password 
summary: 'コンソールで実行したアクションに応じて、 ONTAP資格情報とNetAppサポート サイト (NSS) 資格情報がユーザー ログインに関連付けられている場合があります。関連付けた資格情報を表示および管理できます。たとえば、これらの資格情報のパスワードを変更する場合は、コンソールでパスワードを更新する必要があります。' 
---
= NetApp Consoleログインに関連付けられた資格情報を管理する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
コンソールで実行したアクションに応じて、 ONTAP資格情報とNetAppサポート サイト (NSS) 資格情報がユーザー ログインに関連付けられている場合があります。関連付けた資格情報を表示および管理できます。たとえば、これらの資格情報のパスワードを変更する場合は、コンソールでパスワードを更新する必要があります。



== ONTAP認証情報

コンソールでONTAPクラスターを検出するには、ユーザーはONTAP管理者の認証情報が必要です。ただし、 ONTAP System Manager へのアクセスは、コンソール エージェントを使用しているかどうかによって異なります。

.コンソールエージェントなし
ユーザーは、クラスタのONTAP System Manager にアクセスするために、 ONTAP認証情報を入力するよう求められます。ユーザーはこれらの資格情報をコンソールに保存することを選択できます。これにより、毎回資格情報を入力する必要がなくなります。ユーザー資格情報はそれぞれのユーザーのみに表示され、「ユーザー資格情報」ページから管理できます。

.コンソールエージェントを使用
デフォルトでは、ユーザーはONTAP System Manager にアクセスするためにONTAP認証情報を入力するように求められません。ただし、コンソール管理者（組織管理者ロールを持つ）は、ユーザーにONTAP認証情報の入力を求めるようにコンソールを設定できます。この設定を有効にすると、ユーザーは毎回ONTAP認証情報を入力する必要があります。

link:task-ontap-access-agent.html["詳細情報"^]



== NSS認証情報

NetApp Consoleログインに関連付けられた NSS 資格情報により、サポート登録、ケース管理、およびDigital Advisorへのアクセスが可能になります。

* *サポート > リソース* にアクセスしてサポートに登録すると、NSS 資格情報をログインに関連付けるように求められます。
+
これにより、組織またはアカウントがサポートに登録され、サポート資格が有効になります。サポートに登録し、サポート資格を有効にするには、組織内の 1 人のユーザーのみがNetAppサポート サイト アカウントをログインに関連付ける必要があります。これが完了すると、*リソース* ページにアカウントがサポートに登録されていることが表示されます。

+
https://docs.netapp.com/us-en/bluexp-setup-admin/task-support-registration.html["サポート登録方法を学ぶ"^]

* *管理 > サポート > ケース管理* にアクセスすると、まだ入力していない場合は NSS 資格情報を入力するように求められます。このページでは、NSS アカウントおよび会社に関連付けられたサポート ケースを作成および管理できます。
* コンソールでDigital Advisorにアクセスすると、NSS 資格情報を入力してDigital Advisorにログインするように求められます。


ログインに関連付けられている NSS アカウントについては、次の点に注意してください。

* アカウントはユーザーレベルで管理されるため、ログインした他のユーザーには表示されません。
* Digital Advisorおよびサポート ケース管理に関連付けられる NSS アカウントは、ユーザーごとに 1 つだけです。
* NetAppサポート サイト アカウントをCloud Volumes ONTAPシステムに関連付ける場合は、自分が所属する組織に追加された NSS アカウントからのみ選択できます。
+
NSS アカウント レベルの資格情報は、ログインに関連付けられている NSS アカウントとは異なります。  NSS アカウント レベルの認証情報を使用すると、BYOL を使用してCloud Volumes ONTAPをデプロイし、PAYGO システムを登録し、ソフトウェアをアップグレードできます。

+
link:task-adding-nss-accounts.html["NetApp Console組織またはアカウントで NSS 認証情報を使用する方法の詳細"] 。





== ユーザー資格情報を管理する

ユーザー名とパスワードを更新するか、資格情報を削除して、ユーザー資格情報を管理します。

.手順
. *管理 > 資格情報*を選択します。
. *ユーザー資格情報*を選択します。
. まだユーザー資格情報がない場合は、「*NSS 資格情報の追加*」を選択して、 NetAppサポート サイト アカウントを追加できます。
. [アクション] メニューから次のオプションを選択して、既存の資格情報を管理します。
+
** *資格情報の更新*: アカウントのユーザー名とパスワードを更新します。
** *資格情報の削除*: コンソール ログインに関連付けられている NSS アカウントを削除します。



