= コネクタイメージを取得するための新しい安全なエンドポイント
:allow-uri-read: 




=== コネクタイメージを取得するための新しい安全なエンドポイント

コネクタをインストールするとき、または自動アップグレードが発生するとき、コネクタはリポジトリに接続して、インストールまたはアップグレード用のイメージをダウンロードします。デフォルトでは、コネクタは常に次のエンドポイントに接続します。

* \https://*.blob.core.windows.net
* \https://cloudmanagerinfraprod.azurecr.io


明確な場所を指定できないため、最初のエンドポイントにはワイルドカードが含まれます。リポジトリの負荷分散はサービス プロバイダーによって管理されるため、ダウンロードはさまざまなエンドポイントから発生する可能性があります。

セキュリティ強化のため、コネクタは専用エンドポイントからインストール イメージとアップグレード イメージをダウンロードできるようになりました。

* \https://bluexpinfraprod.eastus2.data.azurecr.io
* \https://bluexpinfraprod.azurecr.io


ファイアウォール ルールから既存のエンドポイントを削除し、新しいエンドポイントを許可して、これらの新しいエンドポイントの使用を開始することをお勧めします。

これらの新しいエンドポイントは、コネクタの 3.9.47 リリース以降でサポートされます。コネクタの以前のリリースとの下位互換性はありません。

次の点に注意してください。

* 既存のエンドポイントは引き続きサポートされます。新しいエンドポイントを使用しない場合は、変更は必要ありません。
* コネクタはまず既存のエンドポイントに接続します。これらのエンドポイントにアクセスできない場合、コネクタは自動的に新しいエンドポイントに接続します。
* 新しいエンドポイントは、次のシナリオではサポートされません。
+
** コネクタが政府地域にインストールされている場合。
** コネクタをBlueXP backup and recoveryまたはBlueXP ransomware protectionと併用する場合。


+
どちらのシナリオでも、既存のエンドポイントを引き続き使用できます。


