= コネクタ 3.9.52
:allow-uri-read: 




=== コネクタ 3.9.52

BlueXPコネクタのこのリリースには、マイナーなセキュリティの改善とバグ修正、およびいくつかの追加の更新が含まれています。

現時点では、3.9.52 リリースは標準モードと制限モードで利用できます。



==== Docker 27 および Docker 28 のサポート

コネクタでは Docker 27 と Docker 28 がサポートされるようになりました。



==== Cloud Volumes ONTAP

コネクタがコンプライアンス違反になったり、14 日以上ダウンしたりしても、 Cloud Volumes ONTAPノードはシャットダウンしなくなりました。 Cloud Volumes ONTAP は、コネクタへのアクセスを失った場合でも、イベント管理メッセージを送信します。この変更は、コネクタが長時間ダウンした場合でも、 Cloud Volumes ONTAP が引き続き動作できるようにするためです。コネクタのコンプライアンス要件は変更されません。



=== BlueXPでKeystone管理が利用可能

BlueXPのNetApp Keystoneベータ版では、 Keystone管理へのアクセスが追加されました。  BlueXPの左側のナビゲーション バーから、 NetApp Keystoneベータ版のサインアップ ページにアクセスできます。



=== BlueXPアイデンティティおよびアクセス管理 (IAM)



==== 新しいストレージ管理の役割

ストレージ管理者、システム正常性スペシャリスト、ストレージ閲覧者の役割が利用可能であり、ユーザーに割り当てることができます。

これらのロールを使用すると、組織内のどのユーザーがストレージ リソースを検出および管理できるかを管理できるほか、ストレージの正常性情報を表示したり、ソフトウェアの更新を実行したりすることもできます。

これらのロールは、次のストレージ リソースへのアクセスを制御するためにサポートされています。

* Eシリーズシステム
* StorageGRIDシステム
* オンプレミスのONTAPシステム


これらのロールを使用して、次のBlueXPサービスへのアクセスを制御することもできます。

* ソフトウェアアップデート
* デジタルアドバイザー
* 運用の回復力
* 経済効率
* 持続可能性


次のロールが追加されました:

* *ストレージ管理者*
+
組織内のストレージ リソースのストレージの健全性、ガバナンス、検出を管理します。このロールは、ストレージ リソースのソフトウェア更新も実行できます。

* *システムヘルススペシャリスト*
+
組織内のストレージ リソースのストレージの健全性とガバナンスを管理します。このロールは、ストレージ リソースのソフトウェア更新も実行できます。このロールでは、作業環境を変更または削除することはできません。

* *ストレージビューア*
+
ストレージの健全性情報とガバナンス データを表示します。

+
link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["アクセス ロールについて学習します。"^]


