= コネクタ 3.9.51
:allow-uri-read: 




=== コネクタ 3.9.51

BlueXPコネクタのこのリリースには、マイナーなセキュリティの改善とバグ修正が含まれています。

現時点では、3.9.51 リリースは標準モードと制限モードで利用できます。



==== コネクタダウンロード用の安全なエンドポイントが、バックアップとリカバリ、およびランサムウェア保護でサポートされるようになりました

バックアップとリカバリまたはランサムウェア保護を使用している場合は、コネクタのダウンロードに安全なエンドポイントを使用できるようになりました。link:https://docs.netapp.com/us-en/bluexp-setup-admin/whats-new.html#new-secure-endpoints-to-obtain-connector-images["コネクタのダウンロードのための安全なエンドポイントについて説明します。"^]



=== BlueXPアイデンティティおよびアクセス管理 (IAM)

* 組織管理者、フォルダ管理者、またはプロジェクト管理者の権限がないユーザーには、ランサムウェア保護にアクセスするために、ランサムウェア保護ロールを割り当てる必要があります。ユーザーには、ランサムウェア保護管理者またはランサムウェア保護閲覧者の 2 つのロールのいずれかを割り当てることができます。
* 組織管理者、フォルダー管理者、またはプロジェクト管理者の権限を持たないユーザーには、 KeystoneにアクセスするためのKeystoneロールを割り当てる必要があります。ユーザーには、 Keystone管理者またはKeystoneビューアーのいずれかのロールを割り当てることができます。
+
link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["アクセス ロールについて学習します。"^]

* 組織管理者、フォルダ管理者、またはプロジェクト管理者のロールを持っている場合は、 Keystoneサブスクリプションを IAM プロジェクトに関連付けることができるようになりました。  Keystoneサブスクリプションを IAM プロジェクトに関連付けると、 BlueXP内でKeystoneへのアクセスを制御できるようになります。

