= コネクタ 3.9.54
:allow-uri-read: 




=== コネクタ 3.9.54

BlueXPコネクタのこのリリースには、セキュリティの改善、バグ修正、および次の新機能が含まれています。

* Cloud Volumes ONTAPサービスのサポート専用のコネクタの透過プロキシのサポート。link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-configuring-proxy.html["透過プロキシの構成について詳しく学びます。"]
* コネクタが Google Cloud 環境にデプロイされているときに、ネットワーク タグを使用してコネクタ トラフィックをルーティングする機能。
* CPU および RAM の使用状況を含む、コネクタのヘルス監視に関する追加の製品内通知。


現時点では、3.9.54 リリースは標準モードと制限モードで利用できます。



=== BlueXPアイデンティティおよびアクセス管理 (IAM)

BlueXPの ID およびアクセス管理では、次の機能が提供されるようになりました。

* プライベート モードでの IAM のサポートにより、 BlueXPサービスおよびアプリケーションに対するユーザー アクセスと権限を管理できます。
* より簡単なナビゲーション、フェデレーション接続を構成するためのより明確なオプション、既存のフェデレーションの可視性の向上など、ID フェデレーションの管理が合理化されます。
* BlueXP backup and recovery、 BlueXP disaster recovery、およびフェデレーション管理のアクセス ロール。




==== プライベートモードでのIAMのサポート

BlueXP はプライベート モードで IAM をサポートするようになり、 BlueXPサービスとアプリケーションに対するユーザー アクセスと権限を管理できるようになりました。この機能強化により、プライベート モードのお客様は、ロールベースのアクセス制御 (RBAC) を活用して、セキュリティとコンプライアンスを強化できます。

link:https://docs.netapp.com/us-en/bluexp-setup-admin/whats-new.html#iam["BlueXPの IAM について詳しく学びます。"]



==== アイデンティティ連携の合理化された管理

BlueXPでは、ID フェデレーションを管理するためのより直感的なインターフェースが提供されるようになりました。これには、より簡単なナビゲーション、フェデレーション接続を構成するためのより明確なオプション、既存のフェデレーションの可視性の向上が含まれます。

ID フェデレーションを通じてシングル サインオン (SSO) を有効にすると、ユーザーは企業の資格情報を使用してBlueXPにログインできるようになります。これにより、セキュリティが向上し、パスワードの使用が減り、オンボーディングが簡素化されます。

新しい管理機能にアクセスするには、既存のフェデレーション接続を新しいインターフェースにインポートするように求められます。これにより、フェデレーション接続を再作成することなく、最新の拡張機能を活用できるようになります。link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-federation-import.html["既存のフェデレーション接続をBlueXPにインポートする方法の詳細について説明します。"]

改善されたフェデレーション管理により、次のことが可能になります。

* フェデレーション接続に複数の検証済みドメインを追加すると、同じ ID プロバイダー (IdP) で複数のドメインを使用できるようになります。
* 必要に応じてフェデレーション接続を無効化または削除し、ユーザー アクセスとセキュリティを制御できます。
* IAM ロールを使用してフェデレーション管理へのアクセスを制御します。


link:https://docs.netapp.com/us-en/bluexp-setup-admin/concept-federation.html["BlueXPの ID フェデレーションの詳細をご覧ください。"]



==== BlueXP backup and recovery、 BlueXP disaster recovery、およびフェデレーション管理の新しいアクセス ロール

BlueXPでは、次の機能とデータ サービスに対する IAM ロールの使用がサポートされるようになりました。

* BlueXP backup and recovery
* BlueXP disaster recovery
* フェデレーション


link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["アクセス ロールの使用について詳しく学習します。"]
