= 
:allow-uri-read: 


コンソール エージェントをインストールしてセットアップしたら、コンソール エージェントが AWS または Azure でアクションを実行するために必要な権限を持つように、クラウド資格情報を追加します。

[role="tabbed-block"]
====
.AWS
--
.開始する前に
これらの AWS 認証情報を作成したばかりの場合は、使用可能になるまでに数分かかることがあります。資格情報をコンソールに追加する前に、数分お待ちください。

.手順
. *管理 > 資格情報*を選択します。
. *組織の資格情報*を選択します。
. *資格情報の追加*を選択し、ウィザードの手順に従います。
+
.. *資格情報の場所*: *Amazon Web Services > エージェントを選択します。
.. *資格情報の定義*: AWS アクセスキーとシークレットキーを入力します。
.. *マーケットプレイス サブスクリプション*: 今すぐサブスクライブするか、既存のサブスクリプションを選択して、マーケットプレイス サブスクリプションをこれらの資格情報に関連付けます。
.. *確認*: 新しい資格情報の詳細を確認し、[*追加*] を選択します。




これで、 https://console.netapp.com["NetAppコンソール"^]コンソール エージェントの使用を開始します。

--
.Azure
--
.開始する前に
これらの Azure 資格情報を作成したばかりの場合は、使用可能になるまでに数分かかることがあります。コンソール エージェントに資格情報を追加する前に、数分間お待ちください。

.手順
. *管理 > 資格情報*を選択します。
. *資格情報の追加*を選択し、ウィザードの手順に従います。
+
.. *資格情報の場所*: *Microsoft Azure > エージェント* を選択します。
.. *資格情報の定義*: 必要な権限を付与する Microsoft Entra サービス プリンシパルに関する情報を入力します。
+
*** アプリケーション（クライアント）ID
*** ディレクトリ（テナント）ID
*** クライアントシークレット


.. *マーケットプレイス サブスクリプション*: 今すぐサブスクライブするか、既存のサブスクリプションを選択して、マーケットプレイス サブスクリプションをこれらの資格情報に関連付けます。
.. *確認*: 新しい資格情報の詳細を確認し、[*追加*] を選択します。




.結果
これで、コンソール エージェントに、ユーザーに代わって Azure でアクションを実行するために必要なアクセス許可が付与されました。これで、 https://console.netapp.com["NetAppコンソール"^]コンソール エージェントの使用を開始します。

--
====