= 
:allow-uri-read: 


.開始する前に
次のものが必要です:

* エージェントをインストールするためのルート権限。
* エージェントからのインターネット アクセスにプロキシが必要な場合のプロキシ サーバーの詳細。
+
インストール後にプロキシ サーバーを構成するオプションがありますが、これを行うにはエージェントを再起動する必要があります。

* プロキシ サーバーが HTTPS を使用する場合、またはプロキシがインターセプト プロキシである場合は、CA 署名証明書。


.タスク概要
NetAppサポート サイトで入手できるインストーラーは、以前のバージョンである可能性があります。インストール後、新しいバージョンが利用可能になると、エージェントは自動的に更新されます。

.手順
. ホストに _http_proxy_ または _https_proxy_ システム変数が設定されている場合は、それらを削除します。
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
これらのシステム変数を削除しないと、インストールは失敗します。

. エージェントソフトウェアを以下からダウンロードしてください。 https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["NetAppサポート サイト"^]それを Linux ホストにコピーします。
+
ネットワークまたはクラウドで使用するための「オンライン」エージェント インストーラーをダウンロードする必要があります。

. スクリプトを実行するための権限を割り当てます。
+
[source, cli]
----
chmod +x NetApp-Console-Agent-<version>
----
+
ここで、<version> はダウンロードしたエージェントのバージョンです。

. インストール スクリプトを実行します。
+
[source, cli]
----
 ./NetApp-Console-Agent-<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>
----
+
--proxy および --cacert パラメータはオプションです。プロキシ サーバーがある場合は、示されているようにパラメータを入力する必要があります。インストーラーはプロキシに関する情報の提供を求めません。

+
両方のオプション パラメータを使用したコマンドの例を次に示します。

+
[source, cli]
----
 ./NetApp-Console-Agent-v4.0.0--proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
----
+
--proxy は、次のいずれかの形式を使用して、エージェントが HTTP または HTTPS プロキシ サーバーを使用するように構成します。

+
** \http://アドレス:ポート
** \http://ユーザー名:パスワード@アドレス:ポート
** \http://ドメイン名%92ユーザー名:パスワード@アドレス:ポート
** \https://アドレス:ポート
** \https://ユーザー名:パスワード@アドレス:ポート
** \https://ドメイン名%92ユーザー名:パスワード@アドレス:ポート
+
次の点に注意してください。

+
*** ユーザーはローカル ユーザーまたはドメイン ユーザーになります。
*** ドメイン ユーザーの場合は、上記のように \ の ASCII コードを使用する必要があります。
*** エージェントは、@ 文字を含むユーザー名またはパスワードをサポートしていません。
*** パスワードに以下の特殊文字が含まれている場合は、その特殊文字の前にバックスラッシュ ( & または ! ) を付けてエスケープする必要があります。
+
例えば：

+
\http://bxpproxyuser:netapp1\!@アドレス:3128





+
--cacert は、エージェントとプロキシ サーバー間の HTTPS アクセスに使用する CA 署名付き証明書を指定します。このパラメータは、HTTPS プロキシ サーバーを指定する場合、またはプロキシがインターセプト プロキシである場合にのみ必要です。

. Podman を使用した場合は、aardvark-dns ポートを調整する必要があります。
+
.. エージェント仮想マシンに SSH で接続します。
.. podman _/usr/share/containers/containers.conf_ ファイルを開き、Aardvark DNS サービス用に選択したポートを変更します。たとえば、54 に変更します。
+
[source, cli]
----
vi /usr/share/containers/containers.conf
...
# Port to use for dns forwarding daemon with netavark in rootful bridge
# mode and dns enabled.
# Using an alternate port might be useful if other DNS services should
# run on the machine.
#
dns_bind_port = 54
...
Esc:wq
----
.. エージェント仮想マシンを再起動します。




. インストールが完了するまでお待ちください。
+
プロキシ サーバーを指定した場合、インストールの最後にエージェント サービス (occm) が 2 回再起動します。

. エージェント仮想マシンに接続しているホストから Web ブラウザを開き、次の URL を入力します。
+
https://_ipaddress_[]

. ログイン後、エージェントを設定します。
+
.. エージェントに関連付けるコンソール組織を指定します。
.. システムの名前を入力します。
.. *安全な環境で実行していますか?* の下で、制限モードを無効のままにします。
+
以下の手順ではコンソールを標準モードで使用する方法について説明しているため、制限モードは無効にしておく必要があります。安全な環境があり、このアカウントをコンソールのバックエンド サービスから切断する場合にのみ、制限モードを有効にする必要があります。もしそうなら、link:task-quick-start-restricted-mode.html["NetApp Consoleを制限モードで使い始めるための手順に従います"] 。

.. *始めましょう*を選択します。



